apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - lightpanda/deployment.yaml
  - lightpanda/imageupdateautomation.yaml
  - lightpanda/service.yaml
  - crw/deployment.yaml
  - crw/imageupdateautomation.yaml
  - crw/service.yaml

configMapGenerator:
  - name: crw-config-toml
    namespace: fastcrw
    files:
      - crw/files/config.toml
