apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcpo-data
  labels:
    app: mcpo
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
