apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: kubernetes-mcp-server
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: keep
  ref:
    tag: 0.1.0
  url: oci://ghcr.io/containers/charts/kubernetes-mcp-server
