---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
  labels:
    app: jellyfin
spec:
  selector:
    matchLabels:
      app: jellyfin
  replicas: 1
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: linuxserver/jellyfin:10.8.10
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: America/New_York
            # - name: JELLYFIN_PublishedServerUrl
            #   value: 10.5.10.60
            # - name: NODE_NAME
            #   valueFrom:
            #     fieldRef:
            #       apiVersion: v1
            #       fieldPath: spec.nodeName
            # - name: POD_NAME
            #   valueFrom:
            #     fieldRef:
            #       apiVersion: v1
            #       fieldPath: metadata.name
            # - name: POD_NAMESPACE
            #   valueFrom:
            #     fieldRef:
            #       apiVersion: v1
            #       fieldPath: metadata.namespace
          ports:
            - containerPort: 8096
              protocol: TCP
            - containerPort: 8920
              protocol: TCP
            - containerPort: 7359
              protocol: UDP
            - containerPort: 1900
              protocol: UDP
          volumeMounts:
            - mountPath: /data/media
              name: media
              readOnly: True
            - mountPath: /config
              name: config
          resources: {}
      restartPolicy: Always
      volumes:
        - name: media
          nfs:
            server: kasumi
            path: /data/Media/
        - name: config
          persistentVolumeClaim:
            claimName: config
