apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstack-config
  namespace: bookstack
data:
  PUID: '1000'
  PGID: '1000'
  TZ: ${GLOBAL_TZ}
  APP_URL: http://wiki.${GLOBAL_DOMAIN}
  DB_HOST: mariadb
  DB_PORT: '3306'
  QUEUE_CONNECTION: ''
