apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack-config
  namespace: bookstack
  labels:
    app: bookstack
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
