apiVersion: v1
kind: Service
metadata:
  name: bookstack
  namespace: bookstack
spec:
  selector:
    app: bookstack
  ports:
    - name: http
      port: 6875
      targetPort: 6875
      protocol: TCP
  type: ClusterIP
