apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bookstack
  namespace: bookstack
  labels:
    app: bookstack
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: bookstack
  serviceName: bookstack
  template:
    metadata:
      labels:
        app: bookstack
    spec:
      containers:
        - name: bookstack
          image: lscr.io/linuxserver/bookstack:26.03.4 # {"$imagepolicy": "flux-system:bookstack-policy"}
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: bookstack-config
          env:
            - name: DB_HOST
              value: "mariadb"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: DB_NAME
            - name: APP_URL
              value: "https://${GLOBAL_DOMAIN_BASE}" # Adjust to your domain, e.g., https://wiki.yourdomain.com
          volumeMounts:
            - name: bookstack-data
              mountPath: /app/bookstack/storage
              readOnly: False
            - name: bookstack-custom
              mountPath: /app/bookstack/public/custom
              readOnly: False
          resources:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 4Gi
              cpu: 500m
      restartPolicy: Always
      readinessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 30
        periodSeconds: 30
        timeoutSeconds: 5
        failureThreshold: 5
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
  volumeClaimTemplates:
    - metadata:
        name: bookstack-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: longhorn
