apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: litellm
type: Opaque
stringData:
  CONNECTION_STRING: postgres://${AI_LITELLM_POSTGRES_USER}:${AI_LITELLM_POSTGRES_PASSWORD}@postgres:5432/${AI_LITELLM_POSTGRES_DB}?sslmode=disable
  POSTGRES_DB: ${AI_LITELLM_POSTGRES_DB}
  POSTGRES_USER: ${AI_LITELLM_POSTGRES_USER}
  POSTGRES_PASSWORD: ${AI_LITELLM_POSTGRES_PASSWORD}
