apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: litellm
type: Opaque
stringData:
  POSTGRES_DB: ${AI_LITELLM_POSTGRES_DB}
  POSTGRES_USER: ${AI_LITELLM_POSTGRES_USER}
  POSTGRES_PASSWORD: ${AI_LITELLM_POSTGRES_PASSWORD}
