apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: mattermost
type: Opaque
stringData:
  CONNECTION_STRING: postgres://${MATTERMOST_POSTGRES_USER}:${MATTERMOST_POSTGRES_PASSWORD}@postgres:5432/${MATTERMOST_POSTGRES_DB}?sslmode=disable
  POSTGRES_DB: ${MATTERMOST_POSTGRES_DB}
  POSTGRES_USER: ${MATTERMOST_POSTGRES_USER}
  POSTGRES_PASSWORD: ${MATTERMOST_POSTGRES_PASSWORD}
