apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeproject-ai
  namespace: codeproject-ai
  labels:
    app: codeproject-ai
spec:
  selector:
    matchLabels:
      app: codeproject-ai
  replicas: 1
  template:
    metadata:
      labels:
        app: codeproject-ai
    spec:
      containers:
      - name: codeproject-ai
        image: codeproject/ai-server:cpu-2.1.10
        ports:
          - containerPort: 32168
        volumeMounts:
          - mountPath: /etc/codeproject/ai 
            name: etc
          - mountPath: /app/modules 
            name: modules
        resources: {}
      volumes:
        - name: etc
          persistentVolumeClaim:
            claimName: etc
        - name: modules
          persistentVolumeClaim:
            claimName: modules
