apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etc
  namespace: codeproject-ai
  labels:
    app: codeproject-ai
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: modules
  namespace: codeproject-ai
  labels:
    app: codeproject-ai
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
