apiVersion: v1
kind: Service
metadata:
  name:  codeproject-ai
  namespace: codeproject-ai
  labels:
    app: codeproject-ai
spec:
  selector:
    app:  codeproject-ai
  # had to use LoadBalancer because it didn't work with an ingress 
  type: LoadBalancer
  ports:
    - name:  http
      port:  32168
      protocol: TCP 
