apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: ingress-nginx
  source:
    repoURL: 'https://github.com/nullvar2000/kubernetes.git'
    targetRevision: main
    path: argocd/apps/ingress-nginx
    directory:
      recurse: true
  destination:
    namespace: '*'
    server: 'https://kubernetes.default.svc'
  syncPolicy: {}