apiVersion: v1
kind: ConfigMap
metadata:
  name: librenms
  namespace: librenms
data:
  CACHE_DRIVER: redis
  LIBRENMS_WEATHERMAP: "false"
  LIBRENMS_WEATHERMAP_SCHEDULE: '*/5 * * * *'
  LOG_IP_VAR: remote_addr
  MAX_INPUT_VARS: "1000"
  MEMORY_LIMIT: 256M
  OPCACHE_MEM_SIZE: "128"
  REAL_IP_FROM: 0.0.0.0/32
  REAL_IP_HEADER: X-Forwarded-For
  REDIS_HOST: redis
  SESSION_DRIVER: redis
  UPLOAD_MAX_SIZE: 16M

