apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: monitoring
  destination:
    namespace: prometheus
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: kube-prometheus-stack
      repoURL: 'https://prometheus-community.github.io/helm-charts'
      targetRevision: 62.7.0
      helm:
        releaseName: prometheus
        valueFiles:
          - $values/argocd/monitoring/prometheus/helm/values.yaml
    - repoURL: 'https://github.com/nullvar2000/kubernetes.git'
      targetRevision: main
      ref: values
  syncPolicy:
    automated: {}
    syncOptions:
      - ServerSideApply=true
