apiVersion: v1
kind: Service
metadata:
  name: librenms
  namespace: librenms
spec:
  selector:
    app: librenms
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  

