---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: library
  namespace: immich
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

