apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homebox
  namespace: argocd
spec:
  project: homebox
  source:
    repoURL: 'https://github.com/nullvar2000/kubernetes.git'
    targetRevision: main
    path: argocd/apps/homebox
  destination:
    namespace: 'homebox'
    server: 'https://kubernetes.default.svc'
  # syncPolicy: 
  #   automated: {}