---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: koillection-uploads
  namespace: koillection
  labels:
    app: koillection
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data
  namespace: koillection
  labels:
    app: koillection
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
