apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: heimdall
  namespace: heimdall
spec:
  secretName: heimdall-tls
  issuerRef:
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
  dnsNames:
    - heimdall.${GLOBAL_DOMAIN}
