apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  labels:
    app: heimdall
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

