apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: intel-plugins
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: release-0.35
  url: https://github.com/intel/intel-device-plugins-for-kubernetes.git
