apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projects
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/nullvar2000/kubernetes.git'
    targetRevision: main
    path: argocd/projects/*
    directory:
      recurse: true
  destination:
    namespace: '*'
    server: 'https://kubernetes.default.svc'
  syncPolicy: {}