apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: setup
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/nullvar2000/kubernetes
      revision: HEAD
      directories:
      - path: argocd/projects/*
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      project: '{{ path.basename }}'
      source:
        repoURL: https://github.com/nullvar2000/kubernetes
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ path.basename }}'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true