apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubooquity-config
  namespace: ubooquity
  labels:
    app: ubooquity
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

