---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbox
  namespace: netbox
  labels:
    app: netbox
spec:
  selector:
    matchLabels:
      app: netbox
  replicas: 1
  template:
    metadata:
      labels:
        app: netbox
    spec:
      containers:
        - name: netbox
          image: linuxserver/netbox:3.2.6
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: America/New_York
            - name: SUPERUSER_EMAIL
              valueFrom: 
                secretKeyRef:
                  name: netbox-app
                  key: superuser_email
                  optional: false
            - name: SUPERUSER_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: netbox-app
                  key: superuser_password
                  optional: false
            - name: ALLOWED_HOST
              valueFrom: 
                secretKeyRef:
                  name: netbox-app
                  key: allowed_host
                  optional: false
            - name: DB_NAME
              valueFrom: 
                secretKeyRef:
                  name: netbox-db-pguser-netbox-db
                  key: dbname
                  optional: false
            - name: DB_USER
              valueFrom: 
                secretKeyRef:
                  name: netbox-db-pguser-netbox-db
                  key: user
                  optional: false
            - name: DB_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: netbox-db-pguser-netbox-db
                  key: password
                  optional: false
            - name: DB_HOST
              valueFrom: 
                secretKeyRef:
                  name: netbox-db-pguser-netbox-db
                  key: host
                  optional: false
            - name: DB_PORT
              valueFrom: 
                secretKeyRef:
                  name: netbox-db-pguser-netbox-db
                  key: port
                  optional: false
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
          ports:
            - containerPort: 8000
      restartPolicy: Always

