apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-config-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/nullvar2000/kubernetes
      revision: HEAD
      directories:
      - path: argocd/projects/cluster-config/*
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      project: cluster-config
      syncPolicy:
        automated: {}
      source:
        repoURL: https://github.com/nullvar2000/kubernetes
        targetRevision: HEAD
        path: '{{ path }}'
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        # namespace: '{{ path.basename }}'