apiVersion: v1
kind: Secret
metadata:
    name: apps-secrets
    namespace: flux-system
type: Opaque
stringData:
    AI_MCP_MCPO_API_KEY: ENC[AES256_GCM,data:PPN6ptrdVE0=,iv:Hzlpm8BvpCNR8FFsKFq81hVG+bX3ud/LjHVIALYrdcQ=,tag:h03nMeJPCAz+BJFBuzglkw==,type:str]
    AI_OPENCLAW_OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:0Fs7CRChIfOzlGw/WLqHiznrFJzVCIe5mOP6QDw9HPpw+ENv3CPNI3NuKFBThbi2uZ+VU1cASEbUzeOnk9HZjg==,iv:964s9sVIdRj6+RMzKcYRYKaYF2sxKRKSDpy3/uO5aA4=,tag:xIBTgrclALFWaHteyO2/XA==,type:str]
    AI_OPENCLAW_OLLAMA_API_KEY: ENC[AES256_GCM,data:0x5dgfNsLnolQPcI,iv:SeLX2Ms9UpWmms1MI1w3mYJEBFF8pbOPtAQ4SovAqbw=,tag:q6LaSr8tgVNTEnmqUmLEow==,type:str]
    AI_OPENWEBUI_OIDC_CLIENT_ID: ENC[AES256_GCM,data:NgZ+FGcqtW6iRQ==,iv:dIkp81l9NcTBboHcdCWx1s6jR900QfafP19rHWxqEEI=,tag:fzW8RSJubvxnzJpTI5i8BA==,type:str]
    AI_OPENWEBUI_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:8WsuVLv8w0YRN46uwHFwP5mRefoXyAl2DVzF8X0/mhM=,iv:LtpvNVRBHDoQlvrFlw7lQhh6YVfsTETLUdMGIcWJgwc=,tag:CeDPfbYY1w7dsPF4z8KY5w==,type:str]
    AI_OPENWEBUI_OIDC_SCOPES: ENC[AES256_GCM,data:4t86LxPBtniGs6SuOxHdu2q2mBq5RKnJVSE=,iv:qW34aAXZezPgv+O0A9kVIjui9MAiGj2GCL5CXgWeN8o=,tag:LIptAet2dcAY0tQcGBiDlQ==,type:str]
    MATTERMOST_S3_ACCESS_KEY: ENC[AES256_GCM,data:EwMe04lkridAc0Qk3Haf6BrK9sU=,iv:rM1vrz941MTe0SYXzKCYmvWs6FT3QaI0Q3lMGPXOOKI=,tag:HTX2gNzlMTUBCSNO2jZtSw==,type:str]
    MATTERMOST_S3_SECRET_KEY: ENC[AES256_GCM,data:210ncsqwXBhA4c/bcnw3s7V+qwuxpzQgagsBfzoeCPypTz3pEe2Gvw==,iv:up/TuU+enphlrWwdQR4lYsiqANdkI5bK6DdPkbBdDWA=,tag:yhXvdnX6lg9Sp8WRwqAlGA==,type:str]
    PAPERLESS_NGX_POSTGRES_DB_NAME: ENC[AES256_GCM,data:sZ6uw7ioI7thGFsKUA==,iv:iLkegNfLKysX1tSemgsVzw1WLgL2ZC+csZAUX8jvQQM=,tag:CKdB/PFonAV6D+9UzdEnvg==,type:str]
    PAPERLESS_NGX_POSTGRES_DB_PASSWORD: ENC[AES256_GCM,data:4iH5frftalKD4M6PS/bufg==,iv:DdEeJbCK1OK/UiGdoGaMAVBJE+H85vYtlo4sU6rU1d0=,tag:Gevb9iHpitT/z8lfi7TheA==,type:str]
    PAPERLESS_NGX_POSTGRES_DB_USER: ENC[AES256_GCM,data:7Yv2sQgsmzoPZ1iK5Ju1,iv:NOj5JI/3o4zJd4cqEnIQHSUybPQwzqfeP+MCpq0/uWk=,tag:lDWTGbFyqKwS6Co384FIYA==,type:str]
    SEARXNG_SECRET: ENC[AES256_GCM,data:GFI90AL2vSS8uqYkn9J978IpIhpdLSHxY6A904kymUE=,iv:ZE5vwbS8JIkgMW8xvCseAuHxdzpA4B2vgSMxi9K61yI=,tag:g4E1oTU/psCR8mEBhlrztw==,type:str]
sops:
    age:
        - recipient: age1738zx2m53wu3u937rveshfe6lpn9gwnj6e9yl3gzyvqrw3gupapscpf8jm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUN1kwVXFMNm1CSUZoODBE
            RWZMOVhZNGl2U1RCNWh1TTFteU91TWNyYVdjCm5GazVLdytSZVZFdGF0Z1JwMkZn
            Tk0wR3ZDU21pV0g3OFpLYUhVTCtqZUUKLS0tIFF6djZBWEkwL0REQ2JYWHR6OEdG
            NUl3NWh0WnNMTG12dlFoQ3BMbUgvQm8KwTv8zR5+uGksyQXyoXG7uATgdVp4vGL9
            TM93Go6xRzByOpBWsWcDAaKV88lDRVYHNIA65TBzvPmCLQGSRDb3dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T00:33:33Z"
    mac: ENC[AES256_GCM,data:2RSUmgnQm+MaVS0HaULVM/sgSJBQ1S52P9bVM8vsjDj7gd/Tv11X/mBKygf7DMMlEeBTluRxhBOm8igoduSSo4zgs4Mdhrg8ifigv0cYKK/fJYAkILAf/lUJQTEdK7VkJMbU6+sQSPZxjzkJ412NKpkn3Z1ov/qUfrpt06uSKig=,iv:mbxAN88kBlWe3VAVe52fe8/fHENZ4ZEvuTVWnfLgLdI=,tag:TidpX7cqaXCsaCL6mC0Ocg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
