apiVersion: v1
kind: Secret
metadata:
    name: apps-secrets
    namespace: flux-system
type: Opaque
stringData:
    AI_MCP_MCPO_API_KEY: ENC[AES256_GCM,data:TN75ZsLvkPA=,iv:m5ZZg1+00Bk5h1kMONZxGowfBiEIhHJnG9z+zetZA2M=,tag:RyYkVJH7DDT44tHXL6VZkA==,type:str]
    AI_HERMES_API_SERVER_KEY: ENC[AES256_GCM,data:2slQ5Dsu96GaLLLcuzE5Jw==,iv:3X5Rffs6+c0GwYSE9WOk+oWuBLhzP4Dx+3Qc1UrGSAc=,tag:NHrpdksAHCJMaJU9LWMlbw==,type:str]
    AI_HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:UUEuTA==,iv:E7A/F4jE2uZdGnUVxm03kSBM2Q42FUSQd03oVX5knDg=,tag:N8F/w4NIZdAbkNGfjwFbKw==,type:str]
    AI_HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:2pGGXjY0+A==,iv:+au6JEa6mFZ8XshuymcmaLEbm5J4oOGIcefBZGQAdUM=,tag:qn03xUu5ZTMC4mf3l7uWIQ==,type:str]
    AI_LITELLM_MASTER_KEY: ENC[AES256_GCM,data:eS1TfpdSRiMyDsWGNfsO66xwb2cFJs4Baxsrio+yzB8m72kG4rI9P7//f6BqAsP4,iv:zJLS6hzoJucr39n2+2ns7YK/eBz5rt50pRcHG/6NjVE=,tag:pQrxxetfPDOFOjTZZOgR+Q==,type:str]
    AI_OPENWEBUI_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:+DQC8AIPa6PdU1WFdCOYHeN+2PkZ79pMxctyuQ/dFSc=,iv:Fwg0h3+iO8gaXDRGKrQi4avW6Wt6VbcR5K7SJF18uVE=,tag:R0ECw+jGxKikJyzln2en2w==,type:str]
    AI_OPENWEBUI_OIDC_SCOPES: ENC[AES256_GCM,data:lTdIz3QtQNZ0hP4WiD6ODDtQyf1Js3m9QqM=,iv:xoXc8YQxTYQK3ZFpHnliEaBRXAtdnNP168hsPlNemU8=,tag:boSS+fBJFxFcOu4Od3kExg==,type:str]
    BOOKSTACK_APP_KEY: ENC[AES256_GCM,data:MkHlTzQZy7YojgCcf/j6ln/jLUISK+lA99yaLv+JBmOYwHTtrZyFEpqHJur1lcdHgrxj,iv:THInzAr3O3eOwoBwmpOLLwPuQ1TaAo4ScQtifEMYeLE=,tag:dIa4WxS6tz0KYV/NrNguzQ==,type:str]
    BOOKSTACK_MARIADB_USER: ENC[AES256_GCM,data:3oFwTcAncFr5ommcOmdU,iv:ETaSu6whoU6XnQCx8XUxGvXP9XKZzxBqfdC0qQBJnnE=,tag:DqR5imGt0twm69dt0pAhVg==,type:str]
    BOOKSTACK_MARIADB_PASSWORD: ENC[AES256_GCM,data:0QXF0EqXgNo/aHDV8fO4Uw==,iv:IjXQFCIYiNyW/8iXlcwP4U0U+ipwDoGyAyNEXUv95Zo=,tag:mUojqwZAe5+hWbJ5kwwWiQ==,type:str]
    BOOKSTACK_MARIADB_DATABASE: ENC[AES256_GCM,data:w+vzK6wAryZv,iv:hALBi9GlvpepLYU19ApdcGZH3l+Lxji+ZjYunP1xblk=,tag:39D741Vw9pSxXLV/QQveRg==,type:str]
    BOOKSTACK_MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:hS70E1XRj8wT17PGwlTTtg==,iv:hYASBh6A/msI2ZK5hftKNBKCqpk/vJRkVrrivcfKnSw=,tag:+Jr289A4YWad7Rqvtw6QAg==,type:str]
    HONCHO_POSTGRES_DB: ENC[AES256_GCM,data:7W8n7w7v,iv:0yVA6hlBgT6rQX3w3wAGoyWZVNYhGeKUDf04H9dHYLk=,tag:+bXHrkF/Bi3hIBA3T49ItA==,type:str]
    HONCHO_POSTGRES_USER: ENC[AES256_GCM,data:+uuWTZFoSo3VRemJ,iv:9FSS15n8JSzgQO3WCAHxS4/r+O7L5T6+LqMVmzUppK4=,tag:OrlOVMo3ksQBxKt/rQ4X5w==,type:str]
    HONCHO_POSTGRES_PASSWORD: ENC[AES256_GCM,data:qKwnBr2IRC87+EYYaXh5uw==,iv:aSOVYHc+7dDYIdhPb27C3pq+z1ps9HBKruE9X2LT2Ls=,tag:+NvFMoGkYYYDWJ9GbK2XLA==,type:str]
    MATTERMOST_POSTGRES_DB: ENC[AES256_GCM,data:l1WfN77hGUbnFg==,iv:9C5nv6mnPPlkKbRrIbE34PWmZPcgZQbezoPVCfJbDLw=,tag:XDANwoSTICtbMyV2V4L5Lg==,type:str]
    MATTERMOST_POSTGRES_USER: ENC[AES256_GCM,data:dEE6RsFzykAD6xkpZCjc3w==,iv:6HqawfU5tMULUjCmT5vFeh8F+2h2n6Q+br8Kb+/5cUk=,tag:ACTPTP4gnUyaFu2fRYtqNg==,type:str]
    MATTERMOST_POSTGRES_PASSWORD: ENC[AES256_GCM,data:wZUpx1K6IX/0xifxudqCCA==,iv:sW29bSVbifrVAiqLy0X9J3wkCM50oq8crn3XBis5ZYc=,tag:6HXwIuabap5iR87vM+LudA==,type:str]
    MATTERMOST_S3_ACCESS_KEY: ENC[AES256_GCM,data:PGoooqlJuuzbzmS5wncGM7jgjLs=,iv:52HYFuOTrUIfpmJk/s71fUYFN17DmKVs8KfbROEwa0M=,tag:8+Sg9AdH3RcT4DEYyQFKRw==,type:str]
    MATTERMOST_S3_SECRET_KEY: ENC[AES256_GCM,data:O3SydYCA0qV167xEi6+3owFZqnXkMsw4f5qzXfugjeIxHSai0heLVQ==,iv:v/LWaaAmUG8wjncVkCIB8KsTIpq8go+nMdsHbAYcysQ=,tag:6lWXoRFBR4RdQdye/GQoZA==,type:str]
    OPENCLAW_MATTERMOST_BOT_TOKEN: ENC[AES256_GCM,data:2aQj/YwRzQID6sTxeMLDuUdUqb82F5q/iqk=,iv:Y8cRFHcBVMfF37Sc5IQqlcek54UySyZKe8A2N8mQekw=,tag:hIYdTFt5TOdzyq4a9aciUg==,type:str]
    PAPERLESS_NGX_POSTGRES_DB_NAME: ENC[AES256_GCM,data:OHAirW55qORQZqpTCA==,iv:2hPvqfcnSCisOkxuE7m5ocz5gCoGo7bvOemeS1H2RbY=,tag:zwhy2BmoG2ul05SIwtYEqQ==,type:str]
    PAPERLESS_NGX_POSTGRES_DB_PASSWORD: ENC[AES256_GCM,data:RuMAa7dgfngLL+v6avid9A==,iv:VWnxeKcea5MJUwYwEaeaSDAl4bVEp1u41hdfonaSQ1c=,tag:SrOpv+TI05Fw7GHkjqWyIw==,type:str]
    PAPERLESS_NGX_POSTGRES_DB_USER: ENC[AES256_GCM,data:QcNZIqO/if0DySC2bylA,iv:pCNwMSCb+R9BD3YjKB4r3s+O1AZV1NBnYsPd8WwOD6I=,tag:eOst6PwiU4lx02pNZIbapA==,type:str]
    PAPERLESS_NGX_PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:c9P6BR1xuQWX+ckzY/Omuogj3juLcZJrKl0AG3AiUKzCAnekrzmasVWJNVWSOOAmXLaXLtHK16TlDoy/37qyMHXgEaPO+E1AEqGscWzL7UpKKmK4Akk=,iv:VqXTJFIOFD0Qjv8q7FlRD/pa2/FVMZnc0kiJAenuYfs=,tag:vSROW1qSHwkBTN9prYbiog==,type:str]
    SEARXNG_SECRET: ENC[AES256_GCM,data:zuMHngKmAf31ufCU2QtiUvZOQRqJ7w4Snkn8/tJfQRo=,iv:GRW8xhP/ObTI4piE1QkurCEl7Zj+x3MEjo2bvSTz6S8=,tag:JqSblydJP+fFxiZJ0NUzAQ==,type:str]
sops:
    age:
        - recipient: age1738zx2m53wu3u937rveshfe6lpn9gwnj6e9yl3gzyvqrw3gupapscpf8jm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSENmeUJ4ZWtnRm5rQmh2
            ZFBYNkJFR2F0cXhLRGdJb1VJRXBGMkdqSkVjCjRjQ0xkaGw4Q1pmd0dtSUhlZUdn
            OTQxNWFFRkN6RXhMRmNGdXc2ZyswMmcKLS0tIENMMG1qZ1oyZnJzR3RNaFR4UzEr
            V0RLNHJGc3V1VENQaXFmL3Q2TmxQVjQKwIlVug7i2UFwXLaGe3uwLJqtpvzp/OLL
            kAnqiT9dxZGKGlqYP1lvA/7Qd6Iou2MrE9vYRFoB4+UYxxpnBODWCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-07T00:24:43Z"
    mac: ENC[AES256_GCM,data:1GbbjY3vH+gE3CYhmca8ugbgY51YUNfzJBtMKXTOMO8hTOFiGDvSgqImEPimHX4KiRmqHoGjaGUYI4TNoboCIUI5vjwyeADuhI8J1seM0VHx+oVKXL+thmSBvsqmdaVY8EpBerMfZN1QP5rAHHyvzt3M7sYv5lTlAsUDrcAYj2Q=,iv:fAejDPpxxqwHFQNHRZ9+vtDfEbEbupkfZ1yPZGm8ljQ=,tag:vitINBf42SvF27mbmjm8Tg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
