apiVersion: v1
kind: Secret
metadata:
    name: apps-secrets
    namespace: flux-system
type: Opaque
stringData:
    AI_MCP_MCPO_API_KEY: ENC[AES256_GCM,data:fG/VR8me58s=,iv:5Ae/OISIBUgWLvly200BNZt8ngESOUZ7rqc8wYfEoV4=,tag:E4+JGDk+4ObjlmK5xpKFxA==,type:str]
    AI_OPENCLAW_OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:uLJJV6uorlE2jO0FRwktiGb8i3n8WqfIH8l81AqPA5RNr0sOlNEIXkoreWr5uAApkbzCZCRH9Gq7HS8YJARfFg==,iv:bqHYVv/erVThz/wyobfbYGnoTG9fzRgd1GwWznQjcJo=,tag:8ZEwP7ZhdQhV40td5IAbQQ==,type:str]
    AI_OPENCLAW_OLLAMA_API_KEY: ENC[AES256_GCM,data:9vRw2X8YqtqAKO9S,iv:/e955E1RXzua9XAYQNM3vt/xzNjnDyK6SVYYyIV5M6k=,tag:lcUEyUVfUnU8qq+ekUtLQQ==,type:str]
    AI_OPENWEBUI_OIDC_CLIENT_ID: ENC[AES256_GCM,data:TSFX2ZyDMQPROA==,iv:BxIvcGpJjSrrqiX5aFFB4y89GBsYWIsFT03pHRGHuIQ=,tag:w2qryAjqkxblkuLt7vwN1A==,type:str]
    AI_OPENWEBUI_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:1LJuiebBjQiyU2STP2IoxS4C+9TJEN6YRaB3gPpV+j4=,iv:7fYyFEg/PdmdRzxo6VtA/0gYrLW8pLBLtSiVGkw6y8g=,tag:LaOrIleZhX+dt8M6nQm06g==,type:str]
    AI_OPENWEBUI_OIDC_SCOPES: ENC[AES256_GCM,data:us9azewrjlzTpXbP0/fhQH4HauLnCvuOQM8=,iv:M32lJd2thWczdmoozvcJggq/Ue66NDLfYNnTGJ32k3M=,tag:Mi7XtTXIQhThcFLk0Rr78g==,type:str]
    BOOKSTACK_APP_KEY: ENC[AES256_GCM,data:0cfUKSLJPKZyRORQOqnScJPv6QFJBIMFhhlpp+enWlxqPGD5rwRrgeFErhqqRaLhOTjB,iv:DUYPQiTLyhE1xiV2fAxXeZp97AWG4ig5znE7T9nPIr0=,tag:PgwQjeBbWtDkJPx8+oDN3A==,type:str]
    BOOKSTACK_MARIADB_USER: ENC[AES256_GCM,data:B9XUPf243j0uhbMU0T00,iv:ACighmC7VAwmBrkMcqNSbK+f9WzbowpjZmsPevIjNoU=,tag:iE6Mv4dGV1IMFySOa3EcNQ==,type:str]
    BOOKSTACK_MARIADB_PASSWORD: ENC[AES256_GCM,data:vS/3qN3k6nicnzpEjrOHuQ==,iv:4s39krPpqrh3YWsmB/7He6TBYvD6LkyUHaOdDsbq9Sw=,tag:WjhnuxKiL34Q43Woct59cA==,type:str]
    BOOKSTACK_MARIADB_DATABASE: ENC[AES256_GCM,data:DQcUGW/+kRL8,iv:tZEzW6A4t9rqOvGuzEHbOONVUGBK/NAzDsoOem+dt3k=,tag:0uCt6egVXmKwJ1NfqDtjBQ==,type:str]
    BOOKSTACK_MARIADB_ROOT_PASSWORD: ENC[AES256_GCM,data:7bDQN/XS7O5ouucqzBIJhg==,iv:hxIwj+zvfRzY89Jx8uaskHAX5TyZJpFeYuGo2L7xYTI=,tag:H2Wghpl6ae/DFjUWUI06XQ==,type:str]
    MATTERMOST_POSTGRES_DB: ENC[AES256_GCM,data:QybT/vPQWsmSmA==,iv:wYF7xGWbbof4dApMERNqYQAJn3sKWi8BYDlyrpeJ5rU=,tag:1kzudiWkswvW7oaZRjubDQ==,type:str]
    MATTERMOST_POSTGRES_USER: ENC[AES256_GCM,data:aAIgj6/m2gIwfrF3gyP2Ew==,iv:pJvCba3iZ9qbrp2FqIDpL6Kp4FSmxbQhtjr9B1pcnwI=,tag:OjdMsotXLhamxCZWoo9Hmg==,type:str]
    MATTERMOST_POSTGRES_PASSWORD: ENC[AES256_GCM,data:URyWG1+rO96L63Afu33kMQ==,iv:elCOrjRXRuL0Y1Do0VvCKCUsUuj2cVEzFlQX1/qEhTI=,tag:8CrDQHRl6Sn98+F1Qw9xJg==,type:str]
    MATTERMOST_S3_ACCESS_KEY: ENC[AES256_GCM,data:LPnr+bqz8kjg+mipgEhR3RLugYA=,iv:jiBb+G31Fg6DEVOXCgzpv8IWYSZUU/8qn2q9Tkm/IAU=,tag:iDwdgfuhNGMS5PPS34ZCuw==,type:str]
    MATTERMOST_S3_SECRET_KEY: ENC[AES256_GCM,data:F7UlpFsXRoqmqersdJEnKBnH92vR4baeLXEPhPRJUOPPlswMrFJ0Ig==,iv:QlV8F/ZBBUQzwfqxQi6LBg/2EH9d+UxTvIOFewSPX6c=,tag:to3doviNYNdmnmzpR24wqQ==,type:str]
    OPENCLAW_MATTERMOST_BOT_TOKEN: ENC[AES256_GCM,data:SUaM/xvFKspdHQJvcViMnuWIC4Mtu8C6Rp4=,iv:R2nQQ5GhEbMEzxvhbf5c77P0GP92p4u6fRAi5V70dbY=,tag:CNZLtQ42virF7LiJnhYzvw==,type:str]
    PAPERLESS_NGX_POSTGRES_DB_NAME: ENC[AES256_GCM,data:sr9qwUDSbpFCTBGJeg==,iv:c/0t9dQ7lrVhX7wE5IIIvx/jyQBx2J2LuIDKkoqgKgA=,tag:f1W/Uwyp1aRswzkWVm9LHQ==,type:str]
    PAPERLESS_NGX_POSTGRES_DB_PASSWORD: ENC[AES256_GCM,data:/oPkM9egLLj4DSp/81qtgg==,iv:TUfvqKlIcXWwQdUcf9pJdRgkntw7AjhI/7UHSQoJdq8=,tag:+UYrc/kBm3DDUmU9wbOUkA==,type:str]
    PAPERLESS_NGX_POSTGRES_DB_USER: ENC[AES256_GCM,data:GBc7OPL+J+c/d1KbRdiw,iv:0WT5PaIjkF/Zy6iP6F2046jh9u3N73udTzrDoN+RLR8=,tag:MvsbcsLDYcmGjRSJ7YGqTw==,type:str]
    SEARXNG_SECRET: ENC[AES256_GCM,data:BCgnhAJqj+2WT7QBwwlgy+b/eWL/i4QWa9cgPH1W1ls=,iv:QARR34sbC8KOOb1y+hmUtas/k60KXiGGlJ/H4ne69bI=,tag:PKa32msJZ30YCYmKOeOXpQ==,type:str]
sops:
    age:
        - recipient: age1738zx2m53wu3u937rveshfe6lpn9gwnj6e9yl3gzyvqrw3gupapscpf8jm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Z1RtN3hqWFBTRmxKSWhW
            cjJ3aG9ndmlJM0x4cDRBM09pWlExeEN2WjBZClZtd0plWWIrbUMzUmNOakxUMzhW
            MUswVkZGKzhmaURoN21aaTcySmM3ancKLS0tIG53ZWJSd1dOM2JYM2RoM1pBT3Fq
            c1NpTVk1Sy9vSDIzY2ZRS0M2dzBFTjQKyq7GR8M/SCNXpbkXpVCpMeESkzz0sdNy
            RRl/DDh6DkP9vT94g55HxNS4h/2s7DnUiR1EurkSUP8ac4dFHPOKYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T23:38:11Z"
    mac: ENC[AES256_GCM,data:7sVKO5GIdZbj8HQyOh79kG0uJjAwcf4husCKBAu1pu2H3FqK5xwd+sX/9XGGVYKqcI7atVktTDxt9es5zOAbSbsXLgqt/QuJre/E5IzFF72SYTRjj6Cl5lKUCEvBKCL51QM7qluzGxobwmI7OP5Uesp6NTpS2DjhN5KJ7nqE2BQ=,iv:5O6roFXzWsP29GZq0OecMnvdIg0+D6Y5pAPXFx/jP+A=,tag:QgZmyQIFOphwQuJp7Eruvg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
