apiVersion: apps/v1
kind: Deployment
metadata:
  name: esphome
  namespace: homeassistant
  labels:
    app: esphome
spec:
  selector:
    matchLabels:
      app: esphome
  replicas: 1
  template:
    metadata:
      labels:
        app: esphome
    spec:
      containers:
      - name: esphome
        image: esphome/esphome:2023.4.4
        env:
        - name: ESPHOME_DASHBOARD_USE_PING
          value: "true"
        - name: ESPHOME_DASHBOARD_RELATIVE_URL
          value: "/"
        volumeMounts:
        - mountPath: /config
          name: config
        resources:  {}
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: esphome-config

