
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
spec:
  interval: 1h
  releaseName: istio-base
  chart:
    spec:
      chart: base
      version: 1.28.3
      sourceRef:
        kind: HelmRepository
        name: istio
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
spec:
  interval: 1h
  dependsOn:
    - name: istio-base
  releaseName: istiod
  chart:
    spec:
      chart: istiod
      version: 1.28.3
      sourceRef:
        kind: HelmRepository
        name: istio
  values:
    profile: ambient
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-cni
spec:
  interval: 1h
  dependsOn:
    - name: istiod
  releaseName: istiod
  chart:
    spec:
      chart: istio-cni
      version: 1.28.3
      sourceRef:
        kind: HelmRepository
        name: istio
  values:
    profile: ambient
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ztunnel
spec:
  interval: 1h
  dependsOn:
    - name: istio-cni
  releaseName: istio-ztunnel
  chart:
    spec:
      chart: istio-ztunnel
      version: 1.28.3
      sourceRef:
        kind: HelmRepository
        name: istio
