general_settings:
  store_model_in_db: true

model_list:
  - model_name: qwen3.8-27b
    litellm_params:
      model: openai/qwen3.8-27b
      api_base: http://192.168.30.254:9931/v1
      api_key: os.environ/LLAMA_SERVER_API_KEY
  - model_name: gemma4-12b
    litellm_params:
      model: openai/gemma-4-12b
      api_base: http://192.168.30.254:9932/v1
      api_key: os.environ/LLAMA_SERVER_API_KEY
  - model_name: gemma4-26b
    litellm_params:
      model: openai/gemma-4-12b
      api_base: http://192.168.30.254:9932/v1
      api_key: os.environ/LLAMA_SERVER_API_KEY
  - model_name: muse-glimmer-30b
    litellm_params:
      model: openai/muse-glimmer-30b
      api_base: http://192.168.30.254:9932/v1
      api_key: os.environ/LLAMA_SERVER_API_KEY

# mcp_servers:
#   searxng_mcp:
#     url: "https://mcp-searxng.${GLOBAL_DOMAIN}/mcp"
#     auth_type: "api_key"
#     auth_value: os.environ/SEARXNG_MCP_HTTP_AUTH_TOKEN
