---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for monitoring applications
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: 'https://github.com/nullvar2000/kubernetes.git'
        revision: HEAD
        directories:
          - path: argocd/monitoring/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: monitoring
      source:
        repoURL: 'https://github.com/nullvar2000/kubernetes.git'
        targetRevision: HEAD
        path: '{{.path.path}}'
        directory:
          exclude: 'helm/values.yaml'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{.path.basename}}'
      syncPolicy:
        # automated: {}
        syncOptions:
          - CreateNamespace=true