apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - github.com/getumbrel/llama-gpt/deploy/kubernetes/
# patchesStrategicMerge:
#   - api.yaml
# resources:
#   - ingress.yaml
#   - pvc.yaml
