apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-models
  namespace: llama-gpt
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

