kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-claim
  namespace: home
spec:
  storageClassName: kasumi-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-site
  namespace: home
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-site
  template:
    metadata:
      labels:
        app: nginx-site
    spec:
      volumes:
        - name: nginx-volume
          persistentVolumeClaim:
            claimName: nginx-claim
      containers:
        - name: nginx-site
          image: nginx:latest
          volumeMounts:
            - name: nginx-volume
              mountPath: /usr/share/nginx/html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: home
spec:
  selector:
    app: nginx-site
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  namespace: home
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: samara.lan
    http:
      paths:
      - path: /nginx
        pathType: Prefix      
        backend:
          service:
            name: nginx-service
            port: 
              number: 8080
