apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - camofox/imageupdateautomation.yaml
  - camofox/service.yaml
  - httproute.yaml
  - imageupdateautomation.yaml
  - service.yaml
  - statefulset.yaml
  - kubernetes-mcp-server-access.yaml

configMapGenerator:
  - name: agent-env
    namespace: hermes-agent
    envs:
      - files/agent.env
  - name: camofox-config
    namespace: hermes-agent
    envs:
      - files/camofox.config