apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - camofox/imageupdateautomation.yaml
  - camofox/service.yaml
  - fastcrw/imageupdateautomation.yaml
  - fastcrw/deployment.yaml
  - fastcrw/service.yaml
  - httproute.yaml
  - imageupdateautomation.yaml
  - rbac.yaml
  - service.yaml
  - statefulset.yaml

configMapGenerator:
  - name: agent-env
    namespace: hermes-agent
    envs:
      - files/agent.env
  - name: agent-scripts
    namespace: hermes-agent
    files:
      - files/gh-pr.py
  - name: camofox-config
    namespace: hermes-agent
    envs:
      - files/camofox.config