---
apiVersion: v1
kind: Service
metadata:
  name:  hermes-agent
  namespace: hermes-agent
spec:
  selector:
    app:  hermes-agent
  type: ClusterIP
  ports:
    - name: hermes-dashboard
      port: 9119
      protocol: TCP
      targetPort: 9119
    - name: code-server
      port: 8443
      protocol: TCP
      targetPort: 8443
      appProtocol: kubernetes.io/ws
