apiVersion: v1
kind: Service
metadata:
  name:  hermes-agent
  namespace: hermes-agent
spec:
  selector:
    app:  hermes-agent
  type: ClusterIP
  ports:
    - name: hermes-agent
      port: 8642
      protocol: TCP
      targetPort: 8642
    - name: code-server
      port: 8443
      protocol: TCP
      targetPort: 8443
