---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-controller
  namespace: unifi-controller
  labels:
    app: unifi-controller
spec:
  selector:
    matchLabels:
      app: unifi-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: unifi-controller
    spec:
      containers:
        - name: unifi-controller
          image: linuxserver/unifi-controller:7.5.176
          imagePullPolicy: Always
          env:
            - name: TZ
              value: America/New_York
          ports:
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8843
              protocol: TCP
            - containerPort: 8880
              protocol: TCP
            - containerPort: 6789
              protocol: TCP
            - containerPort: 3478
              protocol: UDP
            - containerPort: 10001
              protocol: UDP
            - containerPort: 1900
              protocol: UDP
            - containerPort: 5514
              protocol: UDP
          volumeMounts:
            - mountPath: /config
              name: config
          resources: {}
      restartPolicy: Always
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: unifi-controller-config
