apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-controller-config
  namespace: unifi-controller
  labels:
    app: unifi-controller
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

