apiVersion: v1
kind: Service
metadata:
  name:  unifi-controller-tcp
  namespace: unifi-controller
  annotations:
    metallb.universe.tf/allow-shared-ip: 'true'
spec:
  selector:
    app:  unifi-controller
  type: LoadBalancer
  ports:
    - name: https
      port: 8443
      protocol: TCP
    - name: device-communication
      port: 8080
      protocol: TCP
    - name: https-guest
      port: 8843
      protocol: TCP
    - name: http-guest
      port: 8880
      protocol: TCP
    - name: mobile-throughput
      port: 6789
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name:  unifi-controller-udp
  namespace: unifi-controller
  annotations:
    metallb.universe.tf/allow-shared-ip: 'true'
spec:
  selector:
    app:  unifi-controller
  type: LoadBalancer
  ports:
    - name: stun
      port: 3478
      protocol: UDP
    - name: ap-discovery
      port: 10001
      protocol: UDP
    - name: l2-discovery
      port: 1900
      protocol: UDP
    - name: remote-syslog
      port: 5514
      protocol: UDP