apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-server-models
  namespace: llama-server
  labels:
    app: llama-server
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
