apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: litellm
  namespace: flux-system
spec:
  interval: 6h
  url: https://github.com/BerriAI/litellm
  ref:
    tag: 'v1.100.0'
