---
apiVersion: v1
kind: Secret
metadata:
  name: litellm-master-key-secret
  namespace: litellm
type: Opaque
stringData:
  master-key: ${AI_LITELLM_MASTER_KEY}
---
apiVersion: v1
kind: Secret
metadata:
  name: litellm-writer-secret
  namespace: litellm
type: Opaque
stringData:
  username: ${AI_LITELLM_DB_USER}
  password: ${AI_LITELLM_DB_PASSWORD}
