apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: helm
  source:
    chart: metallb
    repoURL: 'https://metallb.github.io/metallb'
    targetRevision: 0.13.10
  destination:
    namespace: metallb-system
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  
