apiVersion: v1
kind: Namespace
metadata:
  name: node-feature-discovery
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: baseline
