apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_KC_BOOTSTRAP_ADMIN_USERNAME}
  KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_KC_BOOTSTRAP_ADMIN_PASSWORD}
