---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: keycloak
  namespace: flux-system
spec:
  image: quay.io/keycloak/keycloak
  interval: 24h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: keycloak-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: keycloak
  policy:
    semver:
      range: ">=26.5.3"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: keycloak-image-update
  namespace: flux-system
spec:
  interval: 6h
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}'
    push:
      branch: fluxcd-keycloak-image-update
  update:
    path: ./flux/apps/keycloak
