apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
stringData:
  POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
  POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
  POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB}
