apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # - httproute.yaml
  # - imageupdateautomation.yaml
  - namespace.yaml
  - secrets.clear.yaml
  - postgres/imageupdateautomation.yaml
  - postgres/service.yaml
  - postgres/statefulset.yaml
  # - paperless-ngx/imageupdateautomation.yaml
  # - paperless-ngx/pvc.yaml
  # - paperless-ngx/service.yaml
  # - paperless-ngx/statefulset.yaml

configMapGenerator:
  - name: paperless-ngx-config
    namespace: paperless-ngx
    envs:
      - files/paperless-ngx-config
