apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
stringData:
  DB_NAME: ${PAPERLESS_NGX_POSTGRES_DB_NAME}
  DB_USER: ${PAPERLESS_NGX_POSTGRES_DB_USER}
  DB_PASSWORD: ${PAPERLESS_NGX_POSTGRES_DB_PASSWORD}
