apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: headlamp
spec:
  secretName: headlamp-tls
  issuerRef:
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
  dnsNames:
    - headlamp.${GLOBAL_DOMAIN}
