apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
spec:
  interval: 1h
  releaseName: headlamp
  chart:
    spec:
      chart: headlamp
      version: 0.39.0
      sourceRef:
        kind: HelmRepository
        name: headlamp
  values:
    config:
      inCluster: true
      enableHelm: true
      watchPlugins: true
      oidc:
        clientID: ${KEYCLOAK_HEADLAMP_CLIENT_ID}
        clientSecret: ${KEYCLOAK_HEADLAMP_CLIENT_SECRET}
        issuerURL: https://keycloak.${GLOBAL_DOMAIN}/realms/${KEYCLOAK_REALM}
        scopes: ${KEYCLOAK_HEADLAMP_SCOPES}
    pluginsManager:
      enabled: true
      configContent: |
        plugins:
          - name: cert-manager
            source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_cert-manager
            version: 0.1.0
          - name: flux
            source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_flux
            version: 0.5.0
          - name: ai-assistant
            source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_ai_assistant
            version: 0.1.0-alpha
        installOptions:
          parallel: true
          maxConcurrent: 2
      baseImage: node:lts-alpine
      version: latest
    persistentVolumeClaim:
      enabled: true
      size: 8Gi
      storageClassName: longhorn
      accessModes: 
        - ReadWriteOnce
    ingress:
      enabled: false
