apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
spec:
  interval: 1h
  releaseName: headlamp
  chart:
    spec:
      chart: headlamp
      version: 0.39.0
      sourceRef:
        kind: HelmRepository
        name: headlamp
  values:
    config:
      inCluster: true
      enableHelm: true
      watchPlugins: true
    pluginsManager:
      enabled: true
      configContent: |
        plugins:
          - name: cert-manager
            source: https://artifacthub.io/packages/headlamp/headlamp-plugins/headlamp_cert-manager
            version: 0.1.0
        installOptions:
          parallel: true
          maxConcurrent: 2
      baseImage: node:lts-alpine
      version: latest
    persistentVolumeClaim:
      enabled: true
      size: 8Gi
      storageClassName: longhorn
      accessModes: 
        - ReadWriteOnce
    ingress:
      enabled: false
