apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
spec:
  interval: 1h
  releaseName: headlamp
  chart:
    spec:
      chart: headlamp
      version: 0.39.0
      sourceRef:
        kind: HelmRepository
        name: headlamp
  values:
    config:
      inCluster: true
      enableHelm: true
    pluginsManager:
      enabled: true
      configContent:
        plugins:
          - name: headlamp_cert-manager
            source: https://github.com/headlamp-k8s/plugins/releases/download/cert-manager-0.1.0/headlamp-k8s-cert-manager-0.1.0.tar.gz
            version: 0.1.0
        installOptions:
          parallel: true
          maxConcurrent: 2
    persistentVolumeClaim:
      enabled: true
      size: 8Gi
      storageClassName: longhorn
      accessModes: 
        - ReadWriteOnce
    ingress:
      enabled: false
