global:
  tolerations: 
    - key: node-role.kubernetes.io/storage
      operator: Exists
      effect: PreferNoSchedule
ingress:
  enabled: false
httproute:
  enabled: true
  hostnames:
    - longhorn.${GLOBAL_DOMAIN}
  parentRefs:
    - name: gateway-api
      namespace: istio-gateway
  path: /
  pathType: PathPrefix
persistence:
  defaultClass: false
  defaultNodeSelector:
    enabled: true
    selector: storage
