global:
  # nodeSelector:
  #   node-role.kubernetes.io/storage: storage
  tolerations: 
    - key: node-role.kubernetes.io/storage
      operator: Exists
      effect: PreferNoSchedule
ingress:
  enabled: true
  ingressClassName: nginx
  host: longhorn.legion.lan
# defaultSettings:
#   createDefaultDiskLabeledNodes: true
persistence:
  defaultClass: false
  defaultNodeSelector:
    enabled: true
    selector: storage