global:
  tolerations: 
    - key: node-role.kubernetes.io/storage
      operator: Exists
      effect: PreferNoSchedule
ingress:
  enabled: false
persistence:
  defaultClass: false
  defaultNodeSelector:
    enabled: true
    selector: storage
