apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piper-data
  namespace: homeassistant
  labels:
    app: piper
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
