---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-data
  labels:
    app: syncthing
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
