
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ollama
  namespace: ollama
spec:
  secretName: ollama-tls
  issuerRef:
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
  dnsNames:
    - ollama.${GLOBAL_DOMAIN}
    - open-webui.${GLOBAL_DOMAIN}
