apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres/imageupdateautomation.yaml
  - postgres/service.yaml
  - postgres/statefulset.yaml
  - helm-release.yaml
  - helm-repo.yaml
  - namespace.yaml
  - secrets.clear.yaml
