---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebox-data
  namespace: homebox
  labels:
    app: homebox
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
