alertmanager:
  # annotations: 
  #   - nginx.ingress.kubernetes.io/rewrite-target: /$2
  ingress:
    enabled: 'true'
    ingressClassName: nginx
    hosts:
      - monitoring.legion.lan
    paths:
      - /alertmanager
    pathType: Prefix
  alertmanagerSpec:
    # externalUrl: http://monitoring.legion.lan/alertmanager
    routePrefix: /alertmanager
grafana:
  env:
    GF_SERVER_ROOT_URL: http://monitoring.legion.lan/grafana
    GF_SERVER_SERVE_FROM_SUB_PATH: 'true'
  # annotations: 
  #   - nginx.ingress.kubernetes.io/rewrite-target: /$2
  ingress:
    enabled: 'true'
    ingressClassName: nginx
    hosts:
      - monitoring.legion.lan
    path: /grafana
prometheus:
  ingress:
    enabled: 'true'
    ingressClassName: nginx
    hosts:
      - monitoring.legion.lan
    paths:
      - /prometheus
    pathType: Prefix
  premetheusSpec:
    externalUrl: http://monitoring.legion.lan/prometheus
    routePrefix: /prometheus