alertmanager:
  ingress:
    enabled: 'true'
    ingressClassName: nginx
    hosts:
      - monitoring.legion.lan
    paths:
      - /alertmanager
  alertmanagerSpec:
    routePrefix: /alertmanager
    
