apiVersion: apps/v1
kind: Deployment
metadata:
  name: musicassistant
  namespace: homeassistant
  labels:
    app: musicassistant
spec:
  selector:
    matchLabels:
      app: musicassistant
  replicas: 1
  template:
    metadata:
      labels:
        app: musicassistant
    spec:
      containers:
        - name: musicassistant
          image: ghcr.io/music-assistant/server:2.5.1
          ports:
            - containerPort: 8095
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /media
              name: media
          resources:  {}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: musicassistant-data
        - name: media
          nfs:
            server: kasumi
            path: /data/Media/

