---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: musicassistant-data
  namespace: homeassistant
  labels:
    app: musicassistant
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
