apiVersion: v1
kind: Service
metadata:
  name:  musicassistant
  namespace: homeassistant
spec:
  selector:
    app:  musicassistant
  type: LoadBalancer
  ports:
    - name: http
      port: 8095
      protocol: TCP
      targetPort: 8095
    - name: http-oauth
      port: 8097
      protocol: TCP
      targetPort: 8097
    - name: snapcast-player
      port : 1704
      protocol: TCP
      targetPort: 1704
    - name: snapcast-web
      port : 1780
      protocol: TCP
      targetPort: 1780
    - name: snapcast-control
      port : 1705
      protocol: TCP
      targetPort: 1705
    - name: slimproto-classic
      port: 9090
      protocol: TCP
      targetPort: 9090
    - name: slimproto-api
      port : 9000
      protocol: TCP
      targetPort: 9000
    - name: slimproto-discovery
      port : 3483
      protocol: TCP
      targetPort: 3483
