---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-data
  namespace: homeassistant
  labels:
    app: whisper
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
