apiVersion: v1
kind: Secret
metadata:
    name: infrastructure-secrets
    namespace: flux-system
type: Opaque
stringData:
    CERT_MANAGER_DNS_API_TOKEN: ENC[AES256_GCM,data:vbPfw9/Vky7y6X+tZqwBPNLjALxleFeDgg3GHw/iFBdEPCIjqGUydA==,iv:0+BeZ5uOxe0deeqG6g1XoznMvdbeQ9Ip0kdHjXBnoRg=,tag:ZIxRI9GqXoHQv3kbm8iv6g==,type:str]
    MONITORING_PROMETHEUS_GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:Brp42yBn+EahIOaaJV2FFw==,iv:+PelpG5y9XLwpKced1a4vKmd8qsX/NQcZjtvmChB7FM=,tag:tPIqgjMtDS64T3phoZztkQ==,type:str]
    MONITORING_PROMETHEUS_MATTERMOST_WEBHOOK_URL: ENC[AES256_GCM,data:Mx+KMcK4QOBUif44no35KcMgRDtRNvGi2NL/zITefchtJi7+8oTok49Vu0fjzAGYj/848cKLxuheILxkw2R3zlI=,iv:Lvw5BWBrbUDLh8AhM9tHr1QL3p5mbBqkV29HdUOvPa4=,tag:18it+9nmiBIXDRdAJst8hA==,type:str]
    MONITORING_PROMETHEUS_RELAY_TOKEN: ENC[AES256_GCM,data:90Wjr074Gp+Ix7uEyrPsTzCUziWAbV7YPGHlU7D48Hw=,iv:TxpzKuknVYxkE5uwqaqEmk2jdHglMZnyxD5jhIo5UlM=,tag:jBZcjaK7EJPJ9Q6due1PeA==,type:str]
    KEYCLOAK_POSTGRES_USER: ENC[AES256_GCM,data:9kq23m73Sns=,iv:kdVsyjpK7OEOL+CkLQRadMySj2kFO3bVxmq69tgQew8=,tag:W7d4TigKFsK+ytSzWuhM2A==,type:str]
    KEYCLOAK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:TtMjZkKDC8RbvDUJQnkMgA==,iv:Fr/OsFe1G2ROxcqLJgPeOxjuHBw4GJPth3s4NBK+9/A=,tag:Av1XY1jh2DCNPBNzTZNdQQ==,type:str]
    KEYCLOAK_POSTGRES_DB: ENC[AES256_GCM,data:7r7Ohg3klrI=,iv:fRk8jDpwN06oeaZFjeQWzJryLApmghmgDgA05nDarnU=,tag:UCSPvJRhyQET4J3UmT8irw==,type:str]
    KEYCLOAK_KC_BOOTSTRAP_ADMIN_USERNAME: ENC[AES256_GCM,data:tDMQK7EPuko=,iv:0eRe1AMR5T3GuK/jLvu+VS+p8Fx/fxFYhGQ+KC2iUOc=,tag:e6JnG0xv1IM2Yk4TN4iGmw==,type:str]
    KEYCLOAK_KC_BOOTSTRAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:UOVYYGjfPnRXba4lJ1syjA==,iv:sIZ08hFwtLMer/aG4uWv4UfG1Dv0qtuYvp5C2fN2zUI=,tag:VxkFwJqj/xqprgltQoeWFg==,type:str]
    KEYCLOAK_HEADLAMP_CLIENT_ID: ENC[AES256_GCM,data:anQneu4=,iv:zUNi+wQM7hVoPWUnuoG7gr1Okru7C2BuVP7M/lSnCvQ=,tag:W49bfBiUjE0HwwEw8dz+HA==,type:str]
    KEYCLOAK_HEADLAMP_CLIENT_SECRET: ENC[AES256_GCM,data:dyHSt1uVrjP/Z+3R36m1SUzaJi4R5rrKRtOL7A40thw=,iv:76eJ+s7IPE3rPyRl7rDBKh+1VTVEYqALfjXU8UjB7GM=,tag:H1runfzKiPNkiATjWzeFgQ==,type:str]
    KEYCLOAK_HEADLAMP_SCOPES: ENC[AES256_GCM,data:RIMhTxRprpKk1Lk=,iv:WUfIG6L+eDY9FiNbOVbXiN7J058Br+OR5FNh7PQNCOE=,tag:QVQcZ83+5L+I9ZgGwFc/FA==,type:str]
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:eoSdsmKluHdxIpg=,iv:YO2SKqaWvzW3b44YQlxLPkK41Djvm9JXMfnkcIQW4YU=,tag:3YCJ4hsKZrOQSOthzuAaAg==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:1LPmVYtIrB8C5Uqm4JzVCQ==,iv:il8J0Sp6dMjncyeB/nfN2FG+cirAPDnwb1h3PGDLWf8=,tag:XLgGAPrBbqJUQSCoS2sIuw==,type:str]
sops:
    age:
        - recipient: age1738zx2m53wu3u937rveshfe6lpn9gwnj6e9yl3gzyvqrw3gupapscpf8jm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSeWdEVHhIblhselVFamtm
            bGVqR0gvNFRZd2tCVUFxM2tJdFhHZTZOUVZnCjFBSEJaNWtaekxEYWlnVStXYjdP
            UFBBakQ0MlFNMHRuOVpac1AycU96Y3cKLS0tIEJQLzF0UjBCZGlYV1RvVkR1SUgv
            QXFlWUNCb0dMUzAxck5aTzM5U2VCMFUKm+f8/Vza1/cXMaj+yuQ0/tTteLnZmMhi
            C97m4J82U3HwfI1xpEDvKulB1tJGdVs3Kinz+Ew5QBAy7lPBY5rokA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-30T18:25:10Z"
    mac: ENC[AES256_GCM,data:ZoARUn+knymcZyk2TiCuvLYMGBaeddYnK0SPblJoFgJ0YFf262c1DirZYc4aCvOzNTGcAMloj8lIRN87vyPhHixgc3n6erOPUsFdYW0YOcoJsmkZhRRZEFACgEBCdj1vGnFyZYP/Z9Ll88lK7Ky24foRQtejajHThmYnR23fDpI=,iv:QrUhYFcsUJFJVmuy2y8Z96zO03XOnPOsNAepn2yO5lw=,tag:u3JWXHduYKXveVn5AL5lMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
