apiVersion: v1
kind: Secret
metadata:
    name: infrastructure-secrets
    namespace: flux-system
type: Opaque
stringData:
    CERT_MANAGER_DNS_API_TOKEN: ENC[AES256_GCM,data:hNpNe7CJnP8Tgfgb0GkMszhyKS85NmqK4zv+ishFdmd1IhQVIZMdVA==,iv:Gst/Fs9D8DZArJkYtVp6LUDuChHf+eg6AQuZsB06ifI=,tag:yANnrkHoyIVee4RVgrjvgA==,type:str]
    MONITORING_PROMETHEUS_GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:5LI7S2xbf4nE1mHReh1JsA==,iv:RyVcjLTdd+3SmzH2byN1IhKS4ZwOq/y7dOQBjKige/g=,tag:gvNv8wruRpBW4uArXqHlGQ==,type:str]
    KEYCLOAK_POSTGRES_USER: ENC[AES256_GCM,data:nC1yAOAH2Oo=,iv:p1L+ZkA8mwiO6etsZ1LsIf+ciVR4yBGlXhKcb3UgZPI=,tag:1oaDYHwz7JU96f/0eaMtLA==,type:str]
    KEYCLOAK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:4XhfrPh3VWS1XxszJqs9vA==,iv:rKnJK4eUKtdlwv0OhE+lZqT7LR39e2+gq48YPZCUWYs=,tag:32tHEYrNGg5gmPLkjI/FkQ==,type:str]
    KEYCLOAK_POSTGRES_DB: ENC[AES256_GCM,data:1G16iGnTSW0=,iv:5ftYgDLHpflvHqKD6HWQg9ZhP9afvUhRdOrJ70eOrlM=,tag:vOyldFqg/oJYHTDkslrdKg==,type:str]
    KEYCLOAK_KC_BOOTSTRAP_ADMIN_USERNAME: ENC[AES256_GCM,data:+LL/CFkPS68=,iv:fP6oKksr6hFQc+hCyOotwFRPWnGOjEn7ejCpsxAvyT0=,tag:rkE100TsZGqiLasES4FObQ==,type:str]
    KEYCLOAK_KC_BOOTSTRAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:9Ik8EHJvntQflj+gi+5VGQ==,iv:VoSwxAt0RJpCAZzGFMU2AJfJhaMf7c3VDLlqk2iY6Cg=,tag:fXu91P2Snodbl0rh4uRjqQ==,type:str]
sops:
    age:
        - recipient: age1738zx2m53wu3u937rveshfe6lpn9gwnj6e9yl3gzyvqrw3gupapscpf8jm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKay9aeTVpOEpSU3N2VDlp
            NVNUSlFWeXZhaXRRQmVhYmtDMG55MitwbGdFClZuT2RPK2hTRmIyR0xUZUloWGx1
            R29rSmdSaTNwWjZqL1kzd3RvSzN3cW8KLS0tIFhkOFRYUk1kcitMR0RJRWJuYTYz
            cEEycGVIZkg2N2ljOGlzNm4rRWFVREEKtIBJBsXcqdMdJbDV2cQyMZdQT95VFC3m
            llfFb9DW2RAIxcKRIBsaimv8bNMdyQoKoiGQM4Z1hZud47mUJXFW+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T00:48:55Z"
    mac: ENC[AES256_GCM,data:w3J/psSHpnpWTOkSIl+MpJ1tfPM/0ELpzPN8BnUqOv71fk7O8jEy4Bsi8G44LP/sCFWKaDXcEMzNbXh9jOuFAJU9lyj4Bf0NJyb+tGvNPlWpZ+Al4UVlKdNSHpV20uXagEPjjBwCFm80Sg3l9z2qhRsUASt9s6+8MnWkwKC5zMo=,iv:pGfEx6JiEpyrM1q8/wNwmXmNVryG2vKDamWfSDoemOA=,tag:b+hazP9WevIwvt8CWBT8vw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
