apiVersion: v1
kind: Secret
metadata:
    name: infrastructure-secrets
    namespace: flux-system
type: Opaque
stringData:
    CERT_MANAGER_DNS_API_TOKEN: ENC[AES256_GCM,data:fSlw4RsABTZLnyyi6x6PbhsLPxURO5krpKhB48vRGCpatV22/qzUPw==,iv:j3rYwYXW8eumkSJY4tEcanI2huG+gbc4FccyPN3aLv0=,tag:LwBDn2hmmLt+lL+IBzhGrA==,type:str]
    MONITORING_PROMETHEUS_GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:AGjwq2+8HzCdghrVbGfRNg==,iv:eK0hLs2Ohwxokb6QOjdGtH06AyBbjFhYYrLiZiZBQDw=,tag:IQdV11TB0KGy6fGNFsBcsA==,type:str]
    KEYCLOAK_POSTGRES_USER: ENC[AES256_GCM,data:QQgphe+F2sY=,iv:vtCpiKUIHGh+GDwNiOxVjdjuPmgJRQ5PgJa8yIlvXx8=,tag:1h+SBvryyApUMJ1SViAtBQ==,type:str]
    KEYCLOAK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:x3jTnQBRwF2at3qYnLVL3Q==,iv:4ma2DUm/oY2YWR/J0NObh8/KS9T308mOa8nb2bMVIK4=,tag:4RDqBXQ987CtePhkznQmEQ==,type:str]
    KEYCLOAK_POSTGRES_DB: ENC[AES256_GCM,data:aGqujJMK1lA=,iv:OlkoqMtJBOxsNrcSp6Jq1wjEH+QYnFpZYoYnDKyBO10=,tag:907gZEqsaSUjN8Nl8pmU5A==,type:str]
    KEYCLOAK_KC_BOOTSTRAP_ADMIN_USERNAME: ENC[AES256_GCM,data:eWvIt+YsfhE=,iv:AQmx/n3qHUF8gS/2/GoZ7GUPHlFeZuq6W7ocikORSns=,tag:HcGOYP9zzNWCXmeP8knCVA==,type:str]
    KEYCLOAK_KC_BOOTSTRAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:tAoCP2+7cbB6JIUPDTYIQg==,iv:+fGT4cBOqzF6d6uMmUI8pJ9a5G3/CLQ0zbujkXS4qDs=,tag:kG4KisIrUdI1NHxnQXIDig==,type:str]
    KEYCLOAK_REALM: ENC[AES256_GCM,data:3KTH5VNA5sTW,iv:ntbQpj0GqySMghAFjQSHI/ciYLHCx1KUeIE1aoiTxa8=,tag:I9T7Q1HdupqEaoeFrsS8CQ==,type:str]
    KEYCLOAK_HEADLAMP_CLIENT_ID: ENC[AES256_GCM,data:gQbo3Jbn500=,iv:1u1hM0+MgCvZrUGNHv0+1g9/3cboCB8MprEnOS4hmzs=,tag:nLcEj/BYP3Ab5Van4Q7YZA==,type:str]
    KEYCLOAK_HEADLAMP_CLIENT_SECRET: ENC[AES256_GCM,data:iyJny+4EBWyYzWGPoxevCrpQkO+dCieH9fgXKgWhV08=,iv:SAReNgYfRONDgZLR0dtEdrtB5w7sGC2O0F8pFa7WBtI=,tag:NSfFdwEyt7KtEqdLR0s+XA==,type:str]
    KEYCLOAK_HEADLAMP_SCOPES: ENC[AES256_GCM,data:/8Drv6StmrnaAj1Qmg==,iv:dctsobjKnAi7BH2n6fY6fyDa00hK3uW5D65bHvwxwa0=,tag:z5mNuAvEhp5b1qphT6d9nA==,type:str]
sops:
    age:
        - recipient: age1738zx2m53wu3u937rveshfe6lpn9gwnj6e9yl3gzyvqrw3gupapscpf8jm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudHNOWEZMR1IzdUpmNkVm
            Qlo3NUxtdE00NkFTRC9HMllqRlhwanJkR1VjClhyUWl0T1h2ZmxXRmd6K292a2pF
            RTZ6cDdoV3VpeldSNStzRXo1VE1aM1kKLS0tIGl5OFZwSzhzcy9ITHZ4UEZVYnIv
            RGJ4Z3VmM3hpdmRIc21McE1CUEUwaVUKIF5CaaW9gqeKQb490VZsd6/HB+9743oQ
            7UTmbptHbZvsTMwAWPa4D9CsgOEWBB66u/aF7OZFo5s2de+T/5Bsdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T19:03:55Z"
    mac: ENC[AES256_GCM,data:/ofWhCVXIYPDQbQIoEoXnjJkx8o7BelGXfznavCtsDXWwKu8ZYtDUc3JtwLqKRwiZFXnJjFfzAzjh4kz7GVYa/vTZOIrbffqVjw4r9huH2pGGrz9oVR1j4DARjF35JEHYgUQHDtgAbUmq0+k6N86BpF3nwaHWo5cPJdiRba+HxQ=,iv:R1FtXFqomzxQFYcOz4mN48PV+cWaiBvMHN2/nx5ZTgE=,tag:vbPuwmmyJovGuoKRIJLF/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
