apiVersion: v1
kind: Secret
metadata:
    name: infrastructure-secrets
    namespace: flux-system
type: Opaque
stringData:
    CERT_MANAGER_DNS_API_TOKEN: ENC[AES256_GCM,data:ZzRCf6aCqbOJiyI0obXqm0JEzY2HGrYiKiOMF2VuKf6oDjOD2NtuBw==,iv:d4ve39Ts1GHBX0BbmIgL1VwBjk6dA2wp5QA0iACqvFI=,tag:hoREMkr13n0Rgc26069r5Q==,type:str]
    MONITORING_PROMETHEUS_GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:4/l1/zxm9iTPbqVdLtLWIw==,iv:FfPUpvVLQTScoB0lYvoxaKj9W2YA/3tkAt8eEW3fV/s=,tag:YuviuUbvfpNGwOK3LFliew==,type:str]
    KEYCLOAK_POSTGRES_USER: ENC[AES256_GCM,data:eOzBgJFz29g=,iv:2O1EqnG9FNpY4oeQQMDyzD/a/0ObKf+yBn3HjWyl0hk=,tag:p5ShbkQB4vRobIrAFxYBcA==,type:str]
    KEYCLOAK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:AzsDBK1dMOlW5gDPh9YHAg==,iv:5NfopRceKy2PVI1kFp92JG/9u3PdeKSWm/VKmPlOlX4=,tag:jU6ThTho1KeNgU1ikxsJYw==,type:str]
    KEYCLOAK_POSTGRES_DB: ENC[AES256_GCM,data:y6Rve84iU1c=,iv:3+5LImh/ZjzHslVe3T5hxtZ+H2Xr9OE/CeXDAEHPSx4=,tag:WEivxgWNBVps17pDWrA7Uw==,type:str]
    KEYCLOAK_KC_BOOTSTRAP_ADMIN_USERNAME: ENC[AES256_GCM,data:Gi8ZstU14Ns=,iv:ORblQ/Rw/VDs+WvucE4tc0SL43ZE1tI43HAedjiGT3E=,tag:vpOynGDeKK+6Knfps6LxlA==,type:str]
    KEYCLOAK_KC_BOOTSTRAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:I5E/NU1oraz9/ZggndN1ng==,iv:J8WowEqIBDt044/5ChR4h47vlxOklQCOpas/4Jpb5p0=,tag:arJT28aISim1w9UGVTd/bw==,type:str]
    KEYCLOAK_REALM: ENC[AES256_GCM,data:ChWxA1Y85yGA,iv:lnWyTc1XZls/ZYuT3e2Umm9P3BwyRhBxpwhTIK5OnZ0=,tag:GkpXfZlwQqAgpPFwObPd4g==,type:str]
    KEYCLOAK_HEADLAMP_CLIENT_ID: ENC[AES256_GCM,data:yIwc3DfQZrc=,iv:oaKRrYyKsVe9ym70Q4lKitYSnWKev/agpqKtmCxkZhc=,tag:LQ+Mef5fOk5wFNwtk8EWpQ==,type:str]
    KEYCLOAK_HEADLAMP_CLIENT_SECRET: ENC[AES256_GCM,data:cozEm/BPBeEmUoGf8du8CNkqiQ6awEPJzpNMQGuyRKM=,iv:8fCmcNsSkU1y5+9uS6UQ4itURKMph9nnNOvwpPw3Xfw=,tag:wCpQtRdHZiU3RTJF8oclMg==,type:str]
    KEYCLOAK_HEADLAMP_SCOPES: ENC[AES256_GCM,data:U1oEGjgzAYzQFzUNBQ==,iv:4lmqb9KlNsKPvzrDO+jQ3d2V2x7OXzLJH6ZqEdWBEb0=,tag:gs2OcKVCfyw/7mj/LlAZ3A==,type:str]
sops:
    age:
        - recipient: age1738zx2m53wu3u937rveshfe6lpn9gwnj6e9yl3gzyvqrw3gupapscpf8jm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUE5TaFRwVEF5YWdJSjQ5
            OEthc05meWhodkpPZmYwaEpCYk1NckhkNWw4ClVTUHpUczFxaDl0bTNxZFpFVGNy
            bzFpckpxYXVVbXVjUkxlU2RQYVRNWEUKLS0tIHhvVTJWZXVwWlA0ZGI5NDhuMEFU
            TDR0K1l0dm9ydEkrTXg0NHZUcXBjSFUK/uXqYTGf7kIzQLTaImxqrnHBM3mYeDqV
            RbSFMPEAWZB8HdUNGGSjs7j3HplynLOq9/4v9HJIqltgSDW34lUV4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-14T16:48:15Z"
    mac: ENC[AES256_GCM,data:6G2tD8LDM5BZNaqTNu+hTaNGbfy6SA5udfs69sjlNkS9XSykZSYSbcn6SqhFTuqTqaAf7sxUQXs3yz5ndrCBGxr5VXYuiQaxerJl1O8/2vSCYK/vl1T+TMv9/5u2W+JhIVI75YU0+QjmXELgnITh7Ld6FQNJsKq78i2AKk1xeUo=,iv:VSrrSEzQRdDH1BWtqKgyzUAYS41hy4AF8irXGXVFtgs=,tag:VfPgmrrGutjGAZysCr0Olw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
