apiVersion: v1
kind: Secret
metadata:
    name: infrastructure-secrets
    namespace: flux-system
type: Opaque
stringData:
    CERT_MANAGER_DNS_API_TOKEN: ENC[AES256_GCM,data:LW94wZy9USTrDyM3jnckbiRJ73CM0sIZUEX3b8TiJM7BD6WElhqs3w==,iv:8G26HHOeMsUuHPSJT0t22e/Q10Zu9iPSz/07227+eYM=,tag:CnVoorwDtCgyDrucCporFQ==,type:str]
    MONITORING_PROMETHEUS_GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:EFt3JToatRh1Pbw23nCSzw==,iv:2bnKG7dfOMuMDIsGYEWG0OD/0Xu3XfT948hLx2KmsvI=,tag:TvSLP876NgzyTovVCtOAaQ==,type:str]
    KEYCLOAK_POSTGRES_USER: ENC[AES256_GCM,data:fQaZk4XBlyU=,iv:9+2ci2VHpWiK4/9ZHN9xWV5New4Yyp6/ZdrGi1aeqI4=,tag:vG3qthMY5UTcGrc2rza5RQ==,type:str]
    KEYCLOAK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:LHgezj3Asz4i/CV/vlEB4A==,iv:+CfeA+r0BfHH6a/m50TJuetsPYJph3/6e2TkO7TlW0s=,tag:WJ0HKDDV70a8fdQceFaGEg==,type:str]
    KEYCLOAK_POSTGRES_DB: ENC[AES256_GCM,data:WFDq9cofgBY=,iv:ZYo/qs2ulslDWEz8rk+vOhWI89UV09qGwiK6T3bBzo4=,tag:gM+w20Tn3nRa1Z5AFrnaQw==,type:str]
    KEYCLOAK_KC_BOOTSTRAP_ADMIN_USERNAME: ENC[AES256_GCM,data:chptZrisJlc=,iv:+rdYXmN60Z6dcogiHV6UTHyF6enNznLzfJDIs8ag9ag=,tag:yl6D4xVvTUOfUzpQbBcetw==,type:str]
    KEYCLOAK_KC_BOOTSTRAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:hRV6MpJ5HxhGuCZtxfPlFw==,iv:eiVaneoix4WAtHRzdwFdPsO80fja/ZaMDrRWCCeHv4U=,tag:l/UsQOplS8XsHYqVJ2Ud/w==,type:str]
    KEYCLOAK_HEADLAMP_CLIENT_ID: ENC[AES256_GCM,data:5p4AB0gBhis=,iv:eMOHgJ3zuO62grHdO1ssXp9BusZn+QukdQV9Dkn4+yI=,tag:0DEgTMaQifWlYH6cxmXDXw==,type:str]
    KEYCLOAK_HEADLAMP_CLIENT_SECRET: ENC[AES256_GCM,data:mVKVVpRd1VSV7LYR8V6v6KKl0KRaz/rxJWDXqRGB0oU=,iv:wvU8c2cDI8SAAL9cwA1Ets7pNQ0AzHZt2uvYRLUEISI=,tag:UeujPvuznX5e+RSWN6AEEA==,type:str]
    KEYCLOAK_HEADLAMP_SCOPES: ENC[AES256_GCM,data:JRjZbMbdtTnK3UE=,iv:CVsMKsOtFkeJZ1KkV34RnOSCQd17H+O2vDGTuZSdeT8=,tag:97hZ4BNDAhzXtn5KryQtVQ==,type:str]
sops:
    age:
        - recipient: age1738zx2m53wu3u937rveshfe6lpn9gwnj6e9yl3gzyvqrw3gupapscpf8jm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNEhKMk5MZDAyUG41TU5H
            Q2huWDlocEZPNk9zTkFJRWZ2QnhMdUc0TGhVClZQY0RaL25DNHJBVTZJbTg5SUtM
            dkZSeTB5SUhKeW5ZTnRZOTJQNXlzb1kKLS0tIFQweDViNFQzQ0tSRU82cko3TURW
            VVZYa2U3ZWdZK1ErMklFMDg1QnhtZ2sKLF3SUGWpeQ4DQWvLt4eGxVFeGUHpj8ku
            4F0pHe9duLf7jNZ7tQD4hkMbp5o3JHCs5DybcELolShGx7pa/U+AGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T16:50:27Z"
    mac: ENC[AES256_GCM,data:IupkzUAG/5E04YLbYjS4PKNa9DaHsN1rBojyJV0Ofs0o5d/+6gaR4/PPX08Ctlypq1tliWIOhOFC73/5YOpmmksWfjO3+54weGoXE2AH40ZqpWggow77TwVJWRMlDG9fsyoDO1RQFxEr2DwaBFLc/p/ked7m2vJJWXqL4dICel8=,iv:Cvhw3MvcAIAtj1u6GCU2Xj9cVOZ+GWs/m6JzldSYW4w=,tag:suNIVJutXMnxX382on1dzg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
