apiVersion: v1
kind: Secret
metadata:
    name: infrastructure-secrets
    namespace: flux-system
type: Opaque
stringData:
    CERT_MANAGER_DNS_API_TOKEN: ENC[AES256_GCM,data:dMS9xgueALOeuX2z8koZuR9wGfNDmEXlskZgc2qUNExOdPO5jXCD1A==,iv:2CrognuhufRXqbUf1jGT0xVTEmdM/F+pvemMsRLcMEo=,tag:9c41CBEtbxDFIu1Ujsbs2w==,type:str]
    MONITORING_PROMETHEUS_GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:J46ZomH1x5btLAsOj1lv4g==,iv:q8eTw/klXw4cbuutiM3V9RtHITg0HGYeRhTx0+Ofu2k=,tag:sDf7HmE2vbKv9Z8A1mgNaA==,type:str]
    KEYCLOAK_POSTGRES_USER: ENC[AES256_GCM,data:NynWBjFzxPM=,iv:WruNHhNKZScMboJkUi0aCmcTQKylpyMTZIw+t77Mbt8=,tag:uG2NazEpMcW0TfhJiDFr5w==,type:str]
    KEYCLOAK_POSTGRES_PASSWORD: ENC[AES256_GCM,data:BsqDLT5MKiV6VNjRuOhiKA==,iv:6/EugwUjdoHa0U3D32AJqOTxrYoXmkSpOAe5Onm5qRk=,tag:oCcaQzAQOBNDKTrvDfrO+g==,type:str]
    KEYCLOAK_POSTGRES_DB: ENC[AES256_GCM,data:RoXtH1q5cSw=,iv:TDsaf4uyrn9diKLgSVAWpXLRA8lxu3li5Hq1vO/WjDo=,tag:v3WfUu6Mazt5+NVk7y38UA==,type:str]
    KEYCLOAK_KC_BOOTSTRAP_ADMIN_USERNAME: ENC[AES256_GCM,data:W8FOOplK50s=,iv:NG1UZew8rFo6zTB1uDpOuMle4TWmHLU8c9nELM+PLvI=,tag:XZ1DWWM7nTMypuIbuGQKvg==,type:str]
    KEYCLOAK_KC_BOOTSTRAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:YLqqKdtlBnIAID5VWIVEXg==,iv:30qP2WMIzi+r+qvQDIDCFEtF2/h9TXwUiRc/huJ0q/Y=,tag:xtL+oWQoGAw/K5zDx8FnGA==,type:str]
    KEYCLOAK_HEADLAMP_CLIENT_ID: ENC[AES256_GCM,data:E4veT9U=,iv:S2kJiWJkCfpGlVjZjAs7AwJ36++jkryIddFFn7yiNSA=,tag:06Ts1rTfR+ri7MHOV1bZNw==,type:str]
    KEYCLOAK_HEADLAMP_CLIENT_SECRET: ENC[AES256_GCM,data:QLyJOYG5QjwTNlpUv80NRZI0566ilgWb8UpZJgSV+TY=,iv:UWg5V9YeHvE6qsCDc8iQ+WtnhXNFoTf13R/fUCEvCI4=,tag:fK3uRes7D6vvgjoyT3ifxw==,type:str]
    KEYCLOAK_HEADLAMP_SCOPES: ENC[AES256_GCM,data:o0wJbnuw3Q1R3kI=,iv:iHnKuKaKWaVTcK/4kDDyddSLsCdNu0rFreTlh7Zk9Fw=,tag:YoPapKy/tdfWfH6DRlaNcw==,type:str]
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:zSI3sv7Wt8iPmFE=,iv:3nfsBzTbcHQH2kwCPMfs5Y+TALd39WKvpvZbzkacjD0=,tag:TM9QaetkjLF5Ww9og6eVQQ==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:eGfXQk0Wjh4GBt5f/4bh5A==,iv:hemneW30nFNit8TA5G7tWzAIW229Nr2XS684f5HWt44=,tag:V207sNiQs64fKg7lS4SnVw==,type:str]
sops:
    age:
        - recipient: age1738zx2m53wu3u937rveshfe6lpn9gwnj6e9yl3gzyvqrw3gupapscpf8jm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxY2luLzBBbGF0dk9DQmk0
            eVlmeUVvUVJZQWUwck9Sd1JBbEQzUWdOWHdNCmd3MTlMcW9tWFRrQzdZdkJ6TWhI
            VmtLY0dSbzBnc0hzS3JQT0lQSW9IeDAKLS0tIHJ3dDJnRVRvSkZVY0xhRmRuNTcv
            Vk1RRlVjUVA1dDZqcG9lTm5QWXo4cE0K+AnkIsPi5I4B5fMQOdSrcRNfvfVPAAni
            X424fGu09FGseGU+fMGR9rLbYWcmT9pb24XuK4BAOnlFWPSIMzPfEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T23:22:24Z"
    mac: ENC[AES256_GCM,data:3VfbDHhbpZIrZt/qf2PdaievVj5ZeIGUrXyMqaOAKicnzXIZy9rDL7s9/t8EtW2WB6yCjCfg1bxjn3tMOHNo+YJgfnoSvn+rmpVy8/GolHm3MwzoDVbFse/QT+LSGNCq+iwk5nz6CtynSJLSjT2zjHKgX6ssgo3zDBYvqb5nMNo=,iv:BRdk92giV4PTJXlU7j5wPDLSPP3/1rVfUNoqyfrvRVg=,tag:SUJPrMV0mCfwyQ7pLyMnRA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
