apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nfd.yaml
  - cert-manager
  - gateway-api
  - headlamp
  - image-common
  - intel-plugins
  - istio
  - keycloak
  - local-path-provisioner
  - monitoring
  - rustfs
  - infrastructure-secrets.sops.yaml
