apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-install
  namespace: argocd
spec:
  project: cert-manager
  source:
    chart: cert-manager
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.12.0
    helm:
      parameters:
        - name: installCRDs
          vale: true
  destination:
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    