apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: librenms-data
  namespace: librenms
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-jiva-csi-default
  resources:
    requests:
      storage: 100Mi

