apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: jellyfin
  source:
    repoURL: 'https://github.com/nullvar2000/kubernetes.git'
    targetRevision: main
    path: argocd/apps/jellyfin
  destination:
    namespace: 'jellyfin'
    server: 'https://kubernetes.default.svc'
  syncPolicy: 
    automated: {}