---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: openclaw
  namespace: flux-system
spec:
  image: ghcr.io/openclaw/openclaw
  interval: 24h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: openclaw-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: openclaw
  policy:
    semver:
      range: ">=2026.4.23-slim"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: openclaw-image-update
  namespace: flux-system
spec:
  interval: 6h
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}'
    push:
      branch: fluxcd-openclaw-image-update
  update:
    path: ./flux/apps/openclaw
