apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - httproute.yaml
  # - imageupdateautomation.yaml
  - namespace.yaml
  - service.yaml
  - statefulset.yaml

configMapGenerator:
  - name: init-config
    namespace: openclaw
    files:
      - files/openclaw.json
      - files/AGENTS.md
