apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openclaw-home
  namespace: openclaw
  labels:
    app: openclaw
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
