apiVersion: v1
kind: Secret
metadata:
  name: openclaw-secrets
  namespace: openclaw
type: Opaque
stringData:
  ANTHROPIC_API_KEY: ""
  GEMINI_API_KEY: ""
  OPENAI_API_KEY: ""
  OPENCLAW_GATEWAY_TOKEN: ${AI_OPENCLAW_OPENCLAW_GATEWAY_TOKEN}
  OPENROUTER_API_KEY: ""
  OLLAMA_API_KEY: ${AI_OPENCLAW_OLLAMA_API_KEY}
  MATTERMOST_BOT_TOKEN: ${OPENCLAW_MATTERMOST_BOT_TOKEN}
  MATTERMOST_URL: http://mattermost.mattermost.svc.cluster.local:8065
