apiVersion: v1
kind: Secret
metadata:
  name: openclaw-secrets
  namespace: openclaw
type: Opaque
stringData:
  ANTHROPIC_API_KEY: ""
  GEMINI_API_KEY: ""
  OPENAI_API_KEY: ""
  OPENCLAW_GATEWAY_TOKEN: ${AI_OPENCLAW_OPENCLAW_GATEWAY_TOKEN}
  OPENROUTER_API_KEY: ""
