apiVersion: v1
kind: Service
metadata:
  name:  gateway
  namespace: openclaw
spec:
  selector:
    app:  openclaw-gateway
  type: ClusterIP
  ports:
    - name: gateway
      port: 18789
      protocol: TCP
      targetPort: 18789
    - name: code-server
      port: 8443
      protocol: TCP
      targetPort: 8443
