---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: paperless-ngx
  labels:
    app: postgres
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: docker.io/library/postgres:16.13-alpine
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: posgres
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: posgres
                  key: DB_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgres-data
              readOnly: False
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 1Gi
      restartPolicy: Always
      volumeClaimTemplates:
        - metadata:
            name: postgres-data
          spec:
            accessModes: 
              - "ReadWriteOnce"
            storageClassName: longhorn
            resources:
              requests:
                storage: 20Gi
