apiVersion: cdi.kubevirt.io/v1beta1
kind: CDI
metadata:
  name: cdi
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  config:
    featureGates:
      - HonorWaitForFirstConsumer
    scratchSpaceStorageClass: longhorn
    podResourceRequirements:
      requests:
        cpu: "100m"
        memory: "60M"
      limits:
        cpu: "750m"
        memory: "2Gi"
