---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates: 
        - ExpandDisks
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}
