---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubevirt.io: ""
    pod-security.kubernetes.io/enforce: "privileged"
  name: kubevirt-hyperconverged
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubevirt.io: ""
  name: virtualmachines
