---
apiVersion: v1
kind: Namespace
metadata:
  name: kubevirt-hyperconverged
  labels:
    kubevirt.io: ""
    pod-security.kubernetes.io/enforce: "privileged"
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: v1
kind: Namespace
metadata:
  name: virtualmachines
  labels:
    kubevirt.io: ""
  annotations:
    argocd.argoproj.io/sync-wave: "0"
