apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helm-repo.yaml
  - helm-release.yaml
  # - ipaddresspool.yaml
  # - l2advertisement.yaml

configMapGenerator:
  - name: helm-values
    namespace: metallb
    files:
      - files/values.yaml
generatorOptions:
  disableNameSuffixHash: true
