apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: librenms
  namespace: argocd
spec:
  project: librenms
  source:
    repoURL: 'https://github.com/nullvar2000/kubernetes.git'
    targetRevision: main
    path: argocd/apps/librenms
  destination:
    namespace: 'librenms'
    server: 'https://kubernetes.default.svc'
  syncPolicy: 
    automated: {}
  ignoreDifferences:
    - jsonPointers:
        - /data
        - /stringData
      group: ""
      kind: Secret
