apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
  namespace: heimdall
  labels:
    app: heimdall
spec:
  selector:
    matchLabels:
      app: heimdall
  replicas: 1 
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      containers:
      - name: heimdall
        image: lscr.io/linuxserver/heimdall:2.4.12 
        env:
        - name: TZ
          value: America/New_York
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - mountPath: /config 
          name: config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: config
