apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: prometheus
  source:
    chart: kube-prometheus-stack
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 51.2.0
    helm:
      releaseName: prometheus
  destination:
    namespace: 'prometheus'
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: prometheus-addons
#   namespace: argocd
# spec:
#   project: prometheus
#   source:
#     repoURL: 'https://github.com/nullvar2000/kubernetes.git'
#     targetRevision: main
#     path: argocd/apps/prometheus
#   destination:
#     namespace: prometheus
#     server: 'https://kubernetes.default.svc'
#   syncPolicy: 
#     automated: {}