apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: monitoring
  sources:
    - chart: kube-prometheus-stack
      repoURL: 'https://prometheus-community.github.io/helm-charts'
      targetRevision: 51.2.0
      helm:
        releaseName: prometheus
        valuesFiles:
          - $values/argocd/apps/prometheus/helm/values.yaml
    - repoURL: 'https://github.com/nullvar2000/kubernetes.git'
      targetRevision: main
      path: argocd/apps/prometheus
      ref: values
    - repoURL: 'https://github.com/nullvar2000/kubernetes.git'
      targetRevision: main
      path: argocd/apps/prometheus
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
