apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: music-assistant
  namespace: homeassistant
  labels:
    app: music-assistant
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: music-assistant
  serviceName: music-assistant
  template:
    metadata:
      labels:
        app: music-assistant
    spec:
      automountServiceAccountToken: false
      containers:
        - name: music-assistant
          image: ghcr.io/music-assistant/server:2.8.3 # {"$imagepolicy": "flux-system:music-assistant-policy"}
          ports:
            - containerPort: 8095
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /media
              name: media
          resources: {}
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: music-assistant-data
        - name: media
          nfs:
            server: kasumi
            path: /data/Media/
