apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: immich
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2
        command:
          - redis-server
          - "/redis/redis.conf"
        ports:
          - containerPort: 6379
        volumeMounts: 
          - mountPath: /redis
            name: config
        resources:  {}
      volumes:
        - name: config
          configMap:
            name: redis-conf
            items:
              - key: redis.conf
                path: redis.conf

