apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: immich
  labels:
    app: redis
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi