---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-infrastructure
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/nullvar2000/kubernetes
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux/infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-infrastructure
  postBuild:
    substituteFrom:
      - kind: Secret
        name: global-secrets
      # - kind: Secret
      #   name: infrastructure-secrets
