
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kanboard
  namespace: kanboard
spec:
  secretName: kanboard-tls
  issuerRef:
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
  dnsNames:
    - kanboard.${GLOBAL_DOMAIN}
