
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wallos
  namespace: wallos
spec:
  secretName: wallos-tls
  issuerRef:
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
  dnsNames:
    - wallos.${GLOBAL_DOMAIN}
