---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: echomuse-controller-data
  namespace: homeassistant
  labels:
    app: echomuse-controller
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
