global:
  tolerations: 
    - key: node-role.kubernetes.io/storage
      operator: Exists
      effect: PreferNoSchedule
ingress:
  enabled: true
  ingressClassName: nginx
  host: longhorn.legion.lan
persistence:
  defaultClass: false
  defaultNodeSelector:
    enabled: true
    selector: storage