apiVersion: v1
kind: Service
metadata:
  name:  mosquitto
  namespace: homeassistant
spec:
  selector:
    app:  mosquitto
  type: LoadBalancer
  ports:
    - name:  plain-mqtt
      port:  1883
      protocol: TCP 
