apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: bookstack
type: Opaque
stringData:
  DB_NAME: ${BOOKSTACK_POSTGRES_DB_NAME}
  DB_USER: ${BOOKSTACK_POSTGRES_DB_USER}
  DB_PASSWORD: ${BOOKSTACK_POSTGRES_DB_PASSWORD}
