apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  namespace: bookstack
type: Opaque
stringData:
  MARIADB_USER: ${BOOKSTACK_MARIADB_USER}
  MARIADB_PASSWORD: ${BOOKSTACK_MARIADB_PASSWORD}
  MARIADB_DATABASE: ${BOOKSTACK_MARIADB_DATABASE}
  MARIADB_ROOT_PASSWORD: ${BOOKSTACK_MARIADB_ROOT_PASSWORD}
