apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallos-db
  labels:
    app: wallos
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallos-logos
  labels:
    app: wallos
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi