apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - secrets.clear.yaml
  - service.yaml

configMapGenerator:
  - name: mattermost-relay-script
    namespace: monitoring
    files:
      - files/relay.py
