apiVersion: v1
kind: Secret
metadata:
  name: mattermost-relay
  namespace: monitoring
  labels:
    app.kubernetes.io/name: mattermost-relay
    app.kubernetes.io/managed-by: flux
type: Opaque
stringData:
  webhook-url: ${MONITORING_PROMETHEUS_MATTERMOST_WEBHOOK_URL}
  relay-token: ${MONITORING_PROMETHEUS_RELAY_TOKEN}
