apiVersion: v1
kind: Service
metadata:
  name: mattermost-relay
  namespace: monitoring
  labels:
    app.kubernetes.io/name: mattermost-relay
    app.kubernetes.io/managed-by: flux
spec:
  selector:
    app.kubernetes.io/name: mattermost-relay
  ports:
    - name: http
      port: 8080
      targetPort: http
