apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: home-cluster
  namespace: default
spec:
  generators:
  - list:
      elements:
      - name: nginx
        # repoURL:  https://github.com/nullvar2000/kubernetes.git
        # revision: master
        # directories:
        #   - path: argocd/apps/*
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/nullvar2000/kubernetes.git
        targetRevision: HEAD
        path: 'argocd/apps/nginx'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{name}}'
