apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-helm-chart
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: core
  destination:
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: cert-manager
      repoURL: 'https://charts.jetstack.io'
      targetRevision: 1.17.1
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/argocd/core/cert-manager/helm/cert-manager/values.yaml
    - repoURL: 'https://github.com/nullvar2000/kubernetes.git'
      targetRevision: main
      ref: values
  syncPolicy:
    automated: {}
  
