---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwakeword-data
  namespace: homeassistant
  labels:
    app: openwakeword
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wyoming-openwakeword
  namespace: homeassistant
  labels:
    app: openwakeword
spec:
  selector:
    matchLabels:
      app: openwakeword
  replicas: 1
  template:
    metadata:
      labels:
        app: openwakeword
    spec:
      containers:
      - name: wyoming-openwakeword
        image: rhasspy/wyoming-openwakeword:1.10.0
        args: ["--preload-model", "ok_nabu"]
        ports:
        - containerPort: 10400
        volumeMounts:
        - mountPath: /data
          name: data
        resources:  {}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: openwakeword-data
---
apiVersion: v1
kind: Service
metadata:
  name:  openwakeword
  namespace: homeassistant
spec:
  selector:
    app:  openwakeword
  type: LoadBalancer
  ports:
    - port:  10400
      protocol: TCP 
      targetPort: 10400
