---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piper-data
  namespace: homeassistant
  labels:
    app: piper
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wyoming-piper
  namespace: homeassistant
  labels:
    app: piper
spec:
  selector:
    matchLabels:
      app: piper
  replicas: 1
  template:
    metadata:
      labels:
        app: piper
    spec:
      containers:
      - name: wyoming-piper
        image: rhasspy/wyoming-piper:1.5.0
        args: ["--voice", "en-gb-southern_english_female-low"]
        ports:
        - containerPort: 10200
        volumeMounts:
        - mountPath: /data
          name: data
        resources:  {}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: piper-data
---
apiVersion: v1
kind: Service
metadata:
  name:  piper
  namespace: homeassistant
spec:
  selector:
    app:  piper
  type: LoadBalancer
  ports:
    - port:  10200
      protocol: TCP 
      targetPort: 10200
