---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piper-data
  namespace: homeassistant
  labels:
    app: piper
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-data
  namespace: homeassistant
  labels:
    app: whisper
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

