apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: bookstack
  labels:
    app: mariadb
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mariadb
  serviceName: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 999
      containers:
        - name: mariadb
          image: docker.io/library/mariadb:12.2.2-ubi10 # {"$imagepolicy": "flux-system:mariadb-12-policy"}
          ports:
            - containerPort: 3306
              protocol: TCP
          envFrom:
            - secretRef:
                name: mariadb
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
              readOnly: false
          resources:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 4Gi
              cpu: 500m
      restartPolicy: Always
      readinessProbe:
        exec:
          command:
            - "sh"
            - "-c"
            - "mysqladmin ping -u $$MYSQL_USER -p$$MYSQL_PASSWORD"
        initialDelaySeconds: 60
        periodSeconds: 30
        timeoutSeconds: 5
        failureThreshold: 5
      livenessProbe:
        exec:
          command:
            - "sh"
            - "-c"
            - "mysqladmin ping -u $$MYSQL_USER -p$$MYSQL_PASSWORD"
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-data
