apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs-jiva
  namespace: argocd
spec:
  project: openebs
  source:
    chart: jiva
    repoURL: 'https://openebs.github.io/jiva-operator'
    targetRevision: 3.5.1
    helm:
      releaseName: openebs-jiva
  destination:
    namespace: openebs
    server: 'https://kubernetes.default.svc'
  # syncPolicy:
  #   automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs-jiva-addons
  namespace: argocd
spec:
  project: openebs
  source:
    repoURL: 'https://github.com/nullvar2000/kubernetes.git'
    targetRevision: main
    path: argocd/apps/openebs
  destination:
    namespace: openebs
    server: 'https://kubernetes.default.svc'
  syncPolicy: 
    automated: {}