apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unifi-controller
  namespace: argocd
spec:
  project: unifi-controller
  source:
    repoURL: 'https://github.com/nullvar2000/kubernetes.git'
    targetRevision: main
    path: argocd/apps/unifi-controller
  destination:
    namespace: 'unifi-controller'
    server: 'https://kubernetes.default.svc'
  syncPolicy: 
    automated: {}