apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: unifi-controller
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for unifi-controller
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  # Only permit applications to deploy to the olm namespaces in the same cluster
  destinations:
  - namespace: 'unifi-controller'
    server: https://kubernetes.default.svc


    

  
