apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallos-db
  namespace: wallos
  labels:
    app: wallos
spec:
  storageClassName: openebs-jiva-csi-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallos-logos
  namespace: wallos
  labels:
    app: wallos
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi