apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
  namespace: argocd
spec:
  project: homeassistant
  source:
    repoURL: 'https://github.com/nullvar2000/kubernetes.git'
    targetRevision: main
    path: argocd/apps/homeassistant
    directory:
      recurse: true
  destination:
    namespace: '*'
    server: 'https://kubernetes.default.svc'
  syncPolicy: 
    automated: {}