---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freedos-disk
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: freedos-14
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: freedos-14
      annotations:
        kubevirt.io/allow-pod-bridge-network-live-migration: "true"
    spec:
      evictionStrategy: LiveMigrate
      domain:
        cpu:
          cores: 1
        resources:
          requests:
            memory: 1G
        machine:
          type: q35
        devices:
          disks:
            - name: freedos-iso
              cdrom:
                bus: sata
              bootOrder: 1
            - name: freedos-disk
              disk:
                bus: virtio
              bootOrder: 2
      volumes:
        - name: freedos-iso
          persistentVolumeClaim:
            claimName: fdiso
        - name: freedos-disk
          persistentVolumeClaim:
            claimName: freedos-disk
