apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
spec:
  project: portainer
  source:
    repoURL: 'https://github.com/nullvar2000/kubernetes.git'
    targetRevision: main
    path: argocd/apps/portainer
  destination:
    namespace: '*'
    server: 'https://kubernetes.default.svc'
  syncPolicy: 
    automated: {}