apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmaps/environment.yaml
  - configmaps/librenms.yaml
  #- deployments/mariadb.yaml
  #- deployments/redis
  - pvcs/mariadb.yaml
  - secrets/mariadb.yaml
  - services/mariadb.yaml
  - services/redis.yaml
  