---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: code-server
  namespace: flux-system
spec:
  image: docker.io/linuxserver/code-server
  interval: 24h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: code-server-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: code-server
  policy:
    semver:
      range: ">=4.117.0"
