---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: vscode
  namespace: flux-system
spec:
  image: lscr.io/linuxserver/code-server
  interval: 24h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: vscode-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: vscode
  policy:
    semver:
      range: ">=4.116.0"
