---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kanboard-data
  labels:
    app: kanboard
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
