apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: primary-pool
  namespace: metallb
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  addresses:
  - 192.168.30.130-192.168.30.200

