apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: primary-advertisement
  namespace: metallb
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  ipAddressPools:
    - primary-pool