
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  secretName: jellyfin-tls
  issuerRef:
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
  dnsNames:
    - jellyfin.${GLOBAL_DOMAIN}
