apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: koillection
  namespace: argocd
spec:
  project: koillection
  source:
    repoURL: 'https://github.com/nullvar2000/kubernetes.git'
    targetRevision: main
    path: argocd/apps/koillection
  destination:
    namespace: 'koillection'
    server: 'https://kubernetes.default.svc'
  syncPolicy: 
    automated: {}