apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: koillection
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for koillection
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - 'https://github.com/nullvar2000/kubernetes.git'
  # Only permit applications to deploy to the olm namespaces in the same cluster
  destinations:
  - namespace: 'koillection'
    server: https://kubernetes.default.svc


    

  
