apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-helm-chart
  namespace: argocd
spec:
  project: core
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: argo-cd
      repoURL: 'https://argoproj.github.io/argo-helm'
      targetRevision: 7.6.2
      helm:
        releaseName: argo-cd
        valueFiles:
          - $values/argocd/core/argocd/helm/values.yaml
    - repoURL: 'https://github.com/nullvar2000/kubernetes.git'
      targetRevision: main
      ref: values
  syncPolicy:
    automated: {}
  
