---
apiVersion: v1
kind: Service
metadata:
  name: lightpanda
  namespace: fastcrw
spec:
  selector:
    app: lightpanda
  type: ClusterIP
  ports:
    - name: http
      port: 9222
      protocol: TCP
      targetPort: 9222
