---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
  namespace: guacamole
  labels:
    app: guacamole
spec:
  selector:
    matchLabels:
      app: guacamole
  replicas: 1
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      containers:
        - name: guacamole
          image: guacamole/guacamole:1.4.0
          imagePullPolicy: IfNotPresent
          env:
            - name: GUACD_HOSTNAME
              value: guacd
            - name: GUACD_PORT
              value: "4822"
            - name: POSTGRES_HOSTNAME
              valueFrom: 
                secretKeyRef:
                  name: guacamole-db-pguser-guacamole-db
                  key: host
                  optional: false
            - name: POSTGRES_PORT
              valueFrom: 
                secretKeyRef:
                  name: guacamole-db-pguser-guacamole-db
                  key: port
                  optional: false
            - name: POSTGRES_DATABASE
              valueFrom: 
                secretKeyRef:
                  name: guacamole-db-pguser-guacamole-db
                  key: dbname
                  optional: false
            - name: POSTGRES_USER
              valueFrom: 
                secretKeyRef:
                  name: guacamole-db-pguser-guacamole-db
                  key: user
                  optional: false
            - name: POSTGRES_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: guacamole-db-pguser-guacamole-db
                  key: password
                  optional: false
          ports:
            - containerPort: 8080
      restartPolicy: Always

