apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: guacamole-db
  namespace: guacamole
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.3-0
  postgresVersion: 14
  instances:
    - name: postgres
      replicas: 1
      dataVolumeClaimSpec:
        storageClassName: nfs-client
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  databaseInitSQL:
    key: init.sql
    name: guac-init-db
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.38-1
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            storageClassName: nfs-client
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
