apiVersion: apps/v1
kind: Deployment
metadata:
  name: librenms
  namespace: librenms
  labels:
    app: librenms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librenms
  template:
    metadata:
      labels:
        app: librenms
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: environment
            - configMapRef:
                name: librenms
            - secretRef:
                name: librenms
          env:
            - name: DB_HOST
              value: mariadb
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: MYSQL_DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: MYSQL_PASSWORD
            - name: DB_TIMEOUT
              value: "60"
          image: librenms/librenms:23.9.1
          name: librenms
          ports:
            - containerPort: 8000
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: librenms-data
      restartPolicy: Always
      volumes:
        - name: librenms-data
          persistentVolumeClaim:
            claimName: librenms-data

