apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: librenms
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - args:
            - mysqld
            - --innodb-file-per-table=1
            - --lower-case-table-names=0
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
          envFrom:
            - configMapRef:
                name: environment
            - secretRef:
                name: mariadb
          image: mariadb:10.5
          name: mariadb
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb-data
      restartPolicy: Always
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-data

