apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui-helm-chart
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: workloads
  destination:
    namespace: ollama
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: open-webui
      repoURL: 'https://helm.openwebui.com/'
      targetRevision: 5.4.0
      helm:
        releaseName: open-webui
        valueFiles:
          - $values/argocd/workloads/ollama/helm/values.yaml
    - repoURL: 'https://github.com/nullvar2000/kubernetes.git'
      targetRevision: main
      ref: values
  syncPolicy:
    automated: {}
