apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms
  namespace: music
  labels:
    app: lms
spec:
  selector:
    matchLabels:
      app: lms
  replicas: 1
  template:
    metadata:
      labels:
        app: lms
    spec:
      containers:
      - name: lms
        image: lmscommunity/logitechmediaserver:stable
        ports:
        - containerPort: 9000
          protocol: TCP
        - containerPort: 9090
          protocol: TCP
        - containerPort: 3483
          protocol: TCP
        - containerPort: 3483
          protocol: UDP
        volumeMounts:
        - mountPath: /config 
          name: config
        - mountPath: /playlist
          name: playlists
        - mountPath: /music
          name: music
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: config
      - name: playlists
        persistentVolumeClaim:
          claimName: playlists
      - name: music
        nfs:
          server: kasumi
          path: /data/Media/
