apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  namespace: music
  labels:
    app: lms
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: playlists
  namespace: music
  labels:
    app: lms
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
