apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-helm-chart
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: core
  destination:
    namespace: longhorn-system
    server: 'https://kubernetes.default.svc'
  sources:
    - chart: longhorn
      repoURL: 'https://charts.longhorn.io'
      targetRevision: 1.8.1
      helm:
        releaseName: longhorn
        valueFiles:
          - $values/argocd/core/longhorn-system/helm/values.yaml
    - repoURL: 'https://github.com/nullvar2000/kubernetes.git'
      targetRevision: main
      ref: values
  syncPolicy:
    automated: {}
