---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-ngx
  labels:
    app: paperless-ngx
spec:
  selector:
    matchLabels:
      app: paperless-ngx
  replicas: 1
  template:
    metadata:
      labels:
        app: paperless-ngx
    spec:
      containers:
        - name: paperless-ngx
          image: ghcr.io/paperless-ngx/paperless-ngx:2.14.7
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: paperless-ngx-config
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: /uploads
              name: paperless-ngx-uploads
              readOnly: False
          resources: {}
      restartPolicy: Always
      volumes:
        - name: paperless-ngx-uploads
          persistentVolumeClaim:
            claimName: paperless-ngx-uploads
