apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner
  namespace: argocd
spec:
  project: nfs-provisioner
  source:
    repoURL: 'https://github.com/nullvar2000/kubernetes.git'
    targetRevision: main
    path: argocd/apps/nfs-provisioner
    directory:
      recurse: true
  destination:
    namespace: '*'
    server: 'https://kubernetes.default.svc'
  syncPolicy: {}