apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: immich
  sources:
    - chart: immich
      repoURL: 'https://immich-app.github.io/immich-charts'
      targetRevision: 0.3.1
      helm:
        releaseName: immich
        valueFiles:
          - $values/argocd/apps/immich/helm/values.yaml
    - repoURL: 'https://github.com/nullvar2000/kubernetes.git'
      targetRevision: main
      ref: values
    - repoURL: 'https://github.com/nullvar2000/kubernetes.git'
      targetRevision: main
      path: argocd/apps/immich
  destination:
    namespace: immich
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    # automated: {}
    syncOptions:
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - kind: Secret
      jsonPointers:
        - /data
        - /stringData
