apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
spec:
  project: immich
  source:
    repoURL: 'https://github.com/nullvar2000/kubernetes.git'
    targetRevision: main
    path: argocd/apps/immich
  destination:
    namespace: immich
    server: 'https://kubernetes.default.svc'
  syncPolicy: {}