apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data
  namespace: uptime-kuma
  labels:
    app: uptime-kuma
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

