apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: typesense-tsdata
  namespace: immich
  labels:
    app: typesense
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi