apiVersion: v1
kind: Service
metadata:
  name: typesense
  namespace: immich
spec:
  selector:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: typesense
  type: ClusterIP
  ports:
    - name:  http
      port:  8108
      protocol: TCP 
