apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: open-webui
spec:
  secretName: open-webui-tls
  issuerRef:
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
  dnsNames:
    - open-webui.${GLOBAL_DOMAIN}
