apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
spec:
  interval: 1h
  releaseName: open-webui
  chart:
    spec:
      chart: open-webui
      version: 10.2.1
      sourceRef:
        kind: HelmRepository
        name: open-webui
  values:
    ollama:
      enabled: false

    pipelines:
      enabled: true

    ingress:
      enabled: false

    persistence:
      enabled: true
      size: 2Gi
      accessModes:
        - ReadWriteOnce
      storageClass: "longhorn"
