apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-webui
spec:
  interval: 1h
  releaseName: open-webui
  chart:
    spec:
      chart: open-webui
      version: 10.2.1
      sourceRef:
        kind: HelmRepository
        name: open-webui
  values:
    ollama:
      enabled: false

    pipelines:
      enabled: true

    tika: 
      enabled: true
    
    managedCertificate:
      enabled: false
    
    ingress:
      enabled: true
      class: nginx
      host: open-webui.${GLOBAL_DOMAIN}
      tls: true

    persistence:
      enabled: true
      size: 2Gi
      accessModes:
        - ReadWriteOnce
      storageClass: "longhorn"

    livenessProbe:
      httpGet:
        path: /health
        port: http
      failureThreshold: 1
      periodSeconds: 10

    readinessProbe:
      httpGet:
        path: /health/db
        port: http
      failureThreshold: 1
      periodSeconds: 10

    startupProbe:
      httpGet:
        path: /health
        port: http
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 20

    sso:
      enabled: true
      enableSignup: true
      enableRoleManagement: true
      oidc:
        enabled: true
        clientId: ${AI_OPENWEBUI_OIDC_CLIENT_ID}
        clientSecret: ${AI_OPENWEBUI_OIDC_CLIENT_SECRET}
        providerUrl: https://keycloak.${GLOBAL_DOMAIN}/realms/${GLOBAL_KEYCLOAK_REALM}/.well-known/openid-configuration
        scopes: ${AI_OPENWEBUI_OIDC_SCOPES}
      roleManagement:
        rolesClaim: "roles"
        allowedRoles: "user"
        adminRoles: "admin"
