---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: camofox
  namespace: flux-system
spec:
  image: ghcr.io/jo-inc/camofox-browser
  interval: 6h
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: camofox-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: camofox
  policy:
    semver:
      range: ">=1.11.2"
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: camofox-image-update
  namespace: flux-system
spec:
  interval: 12h
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}'
    push:
      branch: fluxcd-camofox-image-update
  update:
    path: ./flux/apps/ai/camofox
