apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: uptime-kuma
spec:
  secretName: uptime-kuma-tls
  issuerRef:
    name: letsencrypt-dns01-issuer
    kind: ClusterIssuer
  dnsNames:
    - uptime-kuma.${GLOBAL_DOMAIN}
