apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: codeproject-ai
  namespace: argocd
spec:
  project: codeproject-ai
  source:
    repoURL: 'https://github.com/nullvar2000/kubernetes.git'
    targetRevision: main
    path: argocd/apps/codeproject-ai
  destination:
    namespace: 'codeproject-ai'
    server: 'https://kubernetes.default.svc'
  syncPolicy: 
    automated: {}