apiVersion: v1
kind: Secret
metadata:
  name: litellm
  namespace: litellm
type: Opaque
stringData:
  DATABASE_URL: postgres://${AI_LITELLM_POSTGRES_USER}:${AI_LITELLM_POSTGRES_PASSWORD}@postgres:5432/${AI_LITELLM_POSTGRES_DB}
  LLAMA_SERVER_API_KEY: ${AI_LITELLM_LLAMA_SERVER_API_KEY}
  LITELLM_MASTER_KEY: ${AI_LITELLM_MASTER_KEY}
  LITELLM_SALT_KEY: ${AI_LITELLM_SALT_KEY}
  SEARXNG_MCP_HTTP_AUTH_TOKEN: ${SEARXNG_MCP_HTTP_AUTH_TOKEN}
